### PR TITLE
https: attempt fix crash of init.

### PR DESCRIPTION
**Pull request by Zangetsu38**

### CODE REVIEW

**Review by 1whatleytay — APPROVED** [review]
Zang assures me this fixes the issue. Although I'm not sure how...

**Comment by nn9dev** [comment]
> Zang assures me this fixes the issue. Although I'm not sure how...

As someone who tested it, it eludes me as well. Broke before, works after. C++ shenanigans I suppose...?

**Comment by Croden1999** [comment]
Mr. Zangetsu, is still happened on 3065, i used fastgithub can be running

**Comment by Zangetsu38** [comment]
Why 😭 3 tester have confirme is fixed

**Comment by Croden1999** [comment]
here is log
```
[00:44:53.251] |I| [config::init_config]: backend-renderer: Vulkan
[00:44:53.253] |I| [config::init_config]: log-level: 0
[00:44:53.324] |I| [SDL_main]: Vita3K v0.1.6 3065-69a50120
[00:44:53.324] |I| [SDL_main]: Number of logical CPU cores: 8
[00:44:53.325] |I| [SDL_main]: Available ram memory: 8075 MiB
[00:44:53.490] |I| [renderer::vulkan::VKState::create]: Vulkan device: NVIDIA GeForce GTX 1050
[00:44:53.491] |I| [renderer::vulkan::VKState::create]: Driver version: 466.11.0.0
[00:44:53.492] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled
[00:44:54.075] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Mailbox
[00:44:54.847] |W| [compat::load_compat_app_db]: App with title ID PCSH00241 has an issue but no status label. Please check GitHub issue 1379 and request a status label to be added.
[00:44:55.284] |E| [https::init]: Error establishing SSL connection: error:00000000:lib(0)::reason(0)
[00:44:55.284] |I| [compat::update_compat_app_db]: Applications compatibility database is up to date.
[00:44:55.286] |C| [logging::exception_handler]: Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005). 
[00:44:55.287] |C| [logging::exception_handler]: Read violation at address 0xFFFFFFFFFFFFFFFF.
```

https://user-images.githubusercontent.com/61804715/227276332-fcd5a150-4754-4739-964e-4528164e8623.mp4

**Comment by Zangetsu38** [comment]
What, it said is up to date, with have write erreur on https::init ? 
Is no sense

**Pull request merged**
