### PR TITLE
Replace some assert with possible fix

### PR DESCRIPTION
**Pull request by Co2333**
This fix does NOT fix why it is null but just let the game run. If anything went wrong, revert this commit first. (but should likely be not.

¯\_(ツ)_/¯

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Fail agan lol stop open news pr and just force push correctly after rebased on master

**Comment by Zangetsu38** [comment]
Look your commit name you have inside last commit on master is totaly wrong

**Comment by Co2333** [comment]
well I don't understand what kind of rebase you want.....

ok, I gave up, I'm leaving it here until I got some idea or do make my lovely game working.

**Comment by Co2333** [comment]
> Look your commit name you have inside last commit on master is totaly wrong

I have hard reset the commit in the master branch and brought it to the new branch. Really don't get it.

**Comment by Zangetsu38** [comment]
Look your commit name and commit change

**Comment by Zangetsu38** [comment]
Why juste no edit last commit and remove all change no set by you

**Comment by Co2333** [comment]
close it for now Ill back if the game runs normally.

**Pull request closed without merging**
