### PR TITLE
Implement sceRtcGetTime*_t

### PR DESCRIPTION
**Pull request by VelocityRa**
Used by:
* Starfield-Vita

### CODE REVIEW

**Comment by VelocityRa** [comment]
If you remember from last time, I had said I didn't do this because with the current project structure they would go in `util.cpp`, which is weird.
Do you still think it's ok? Another solution would be to make rtc stuff its own project.

**Comment by petmac** [comment]
That is probably true.

At the moment this is in the host module, so it shouldn't cause any change of dependencies if rtc implementations stay there but move to a .cpp file.

I worry a little about making rtc its own project as I don't want to end up in the same place as before with hundreds of libraries that take ages to load and build in Visual Studio.

**Comment by VelocityRa** [comment]
Yeah it's in host not utils, my bad. Also you're right about rtc being its own module, it's not large enough to warrant it.

I put them in a _new_ .cpp file instead of host.cpp, which I guess violates the projects structure? Even if so, I think it's better this way, thoughts?

**Comment by VelocityRa** [comment]
Bump @petmac.

**Pull request merged**
