### PR TITLE
kernel: reimplement run_callback

### PR DESCRIPTION
**Pull request by sunho**
This should be without erratic bug when calling lle callback function (after running one callback function it will go outside the interrupt handler) 

I used cpu instance pool to solve the problem. It grabs one cpu instance from the pool, execute the lle code on it, and return instance to the pool. If service call is made inside lle callback code, it should work fine, since it's brand new cpu instance separate from the original cpu instance of the thread (the one called something like sceNpCheckCallback) The cursed nested loop like service call -> callback -> service call -> callback -> service call also work fine. But, if the depth is higher than the volume of cpu pool, it would break. I set it to 10 for now. I think it should work fine as long as there's no infinite recursion or something.

The reason for pooling is because of unicorn instance tlb cache. The instance holds its own jit cache, and the overhead for translation is quite high. Pooling can help this. However, since we almost randomly draw an instance from the pool, the instance might not have helpful jit cache. Solving this problem is interesting further work. We can try using thread_id to draw more appropriate instance. (e.g. this instance was used by thread 3 before, so it should have jit cache helpful for lle callback execed from thread 3)

### CODE REVIEW

**Comment by sunho** [comment]
LBP and downfall (network checking game in general) are affected by this pr. I'd appreciate if someone can test them. 

I also want to confirm that the issue related to https://github.com/Vita3K/Vita3K/pull/1138 is okay with this. @bookmist

**Comment by Zangetsu38** [comment]
same for killzone, npcheckcallback, and some other stop boot after this get, i try

**Comment by sunho** [comment]
downwell boots fine for me. But the graphics has regressed in master build.

**Comment by Zangetsu38** [comment]
yes, i have same, render is very darkness, diffucult to see

**Comment by Zangetsu38** [comment]
i see regression on video playing for Hatsune mikudiva F, i now crash on start play video

**Comment by frangarcj** [comment]
I still don't get how the arguments are passed. Can you explain it?

**Comment by bookmist** [comment]
> I also want to confirm that the issue related to #1138 is okay with this. @bookmist

Looks ok. Many thanks, I hoped someone rewrite this part of my code properly. Some of my old code was not cleaned, so there is the patches

` vita3k/modules/SceAvPlayer/SceAvPlayer.cpp | 1 -
 1 file changed, 1 deletion(-)

diff --git a/vita3k/modules/SceAvPlayer/SceAvPlayer.cpp b/vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
index 725e472c..370b3fba 100644
--- a/vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
+++ b/vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
@@ -186,7 +186,6 @@ EXPORT(int, sceAvPlayerAddSource, SceUID player_handle, const char *path) {
 EXPORT(int, sceAvPlayerClose, SceUID player_handle) {
     const PlayerPtr &player_info = lock_and_find(player_handle, host.kernel.players, host.kernel.mutex);
     run_event_callback(host, thread_id, player_info, SCE_AVPLAYER_STATE_STOP, 0, Ptr<void>(0));
-    assert(player_info->callback_depth_counter == 0);
     host.kernel.players.erase(player_handle);
     return 0;
 }`

` vita3k/kernel/include/kernel/state.h | 2 --
 1 file changed, 2 deletions(-)

diff --git a/vita3k/kernel/include/kernel/state.h b/vita3k/kernel/include/kernel/state.h
index 08d136b0..fb12a879 100644
--- a/vita3k/kernel/include/kernel/state.h
+++ b/vita3k/kernel/include/kernel/state.h
@@ -234,8 +234,6 @@ struct PlayerInfoState {
     SceAvPlayerMemoryAllocator memory_allocator;
     SceAvPlayerFileManager file_manager;
     SceAvPlayerEventManager event_manager;
-    SceUID player_callback_thread_id = SCE_KERNEL_ERROR_ILLEGAL_THREAD_ID;
-    uint32_t callback_depth_counter = 0;
 };
 
 typedef std::shared_ptr<PlayerInfoState> PlayerPtr;
`

**Comment by bookmist** [comment]
> 
> 
> I still don't get how the arguments are passed. Can you explain it?

Arguments passed in first 4 registers of CPU. Fifth and more arguments should be puched into stack, but i don't know how to do it.

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
