### PR TITLE
CI: remove deprecated `set-output` commands

### PR DESCRIPTION
**Pull request by illusion0001**

### CODE REVIEW

**Comment by illusion0001** [comment]
https://github.com/illusion0001/Vita3K/actions/runs/3976334913

**Comment by Zangetsu38** [comment]
4 commit 💀

**Comment by illusion0001** [comment]
Will force push later, squash merge is always an option

**Comment by Zangetsu38** [comment]
I know’ but here just learn git, squash, and if yiu édit, using edit last commit and force push

**Comment by illusion0001** [comment]
Force pushied

**Comment by Zangetsu38** [comment]
@IllusionMan1212 can review ?

**Review by IllusionMan1212 — APPROVED** [review]
looks good

**Pull request merged**
