### PR TITLE
Time machiner

### PR DESCRIPTION
**Pull request by Ristellise**
This PR implements:
- sceScreenShot [Not Finished]
- load_self fail safes. [For now, it stops people from loading encrypted SELFs. And preoviding a helpful message why we cant do it yet.]

**This is marked as draft as sceScreenShot isn't done yet.**

### CODE REVIEW

**Comment by pent0** [comment]
If you want all of your commit to be present in master before merge name them compatible with the rules

**Comment by Rinnegatamante** [comment]
where's sceScreenshot? Did you forget to push its implementation?

**Comment by pent0** [comment]
He said its not touched, so draft

Vào 17:18, T.4, 7 Th8, 2019 Rinnegatamante <notifications@github.com> đã
viết:

**Comment by Ristellise** [comment]
> where's sceScreenshot? Did you forget to push its implementation?

I'm mainly not sure of where to put the implementation mainly the structs because I need a struct for each game session on boot that I can access.

I could use a static but I feel that's bad practice.  
I have an idea on how to implement it but just not sure where.

**Comment by pent0** [comment]
Use "host"

Vào 17:22, T.4, 7 Th8, 2019 Shinon <notifications@github.com> đã viết:

**Comment by pent0** [comment]
The macro you see have a parameter named "host". It contains all emulator
component state, inclduing a state called "display". Display state contains
current frame buf pointer and info. Should be what you want.

Vào 17:23, T.4, 7 Th8, 2019 BentVEVO . <fewdspuckrito@gmail.com> đã viết:

**Comment by Ristellise** [comment]
Closing This PR, Mainly lack of motivation to continue working on it,

**If anyone want to implement it, feel free to do so.**

**Pull request closed without merging**
