### PR TITLE
SceGxm: init surface correctly in sceGxmDepthStencilSurfaceInitDisabled

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by sunho** [comment]
https://github.com/Vita3K/Vita3K/blob/aebc9fb0fd25dbf399a4e3f97fd2135609fb42fc/vita3k/gxm/include/gxm/types.h#L1053

Shouldn't this set it 1.0?

**Comment by scribam** [comment]
For the first change, yes. For the second one, you have a `memset(surface, 0, sizeof(*surface));` before so I assume it sets the value to 0.0

**Review by sunho — CHANGES_REQUESTED** [review]
Can you change sceGxmDepthStencilSurfaceInitDisabled to copy default initialized 
 SceGxmDepthStencilSurface  struct like sceGxmDepthStencilSurfaceInit do? That way we can just use the struct definition for changing default value.

**Comment by scribam** [comment]
@sunho done, I have used the code from sceGxmDepthStencilSurfaceInit to initialize the structures. Please have a look again

**Review by sunho — APPROVED** [review]

**Pull request merged**
