### PR TITLE
gui/initial setup: Fix respect aspect ratio.

### PR DESCRIPTION
**Pull request by Zangetsu38**
- gui/initial setup: Fix respect aspect ratio.
Improve size of column of select language.
Save config any time press on next.
Add two gui setting.

### CODE REVIEW

**Comment by Macdu** [comment]
The two settings have absolutely nothing to do with aspect ratio?

**Comment by Zangetsu38** [comment]
> The two settings have absolutely nothing to do with aspect ratio?

No, i juste adding it in same time, no need separe commit if change is inside same file

**Comment by Macdu** [comment]
Tell why would I expect a commit whose name is "Fix aspect ratio" to add config options to the initial setup?

Also why would the initial setup need to be 16:9? It looks nothing like the PS Vita initial setup anyway, is some simple text, buttons and scrolling list and this just reduces the size for the initial setup gui and add black bars to the side.

**Comment by Zangetsu38** [comment]
> Tell why would I expect a commit whose name is "Fix aspect ratio" to add config options to the initial setup?
> 
> Also why would the initial setup need to be 16:9? It looks nothing like the PS Vita initial setup anyway, is some simple text, buttons and scrolling list and this just reduces the size for the initial setup gui and add black bars to the side.

Eu ? Is litteraly writed in second line

And same other... i want all respect psvita size, is no complicated here...
My all gui code writed is full based on interface of pscita for all, so is full normal
No idea why you have problèm with just respect original proportion of élément for keep good render and proper
Currently is broken, i fix it, that all

**Pull request closed without merging**
