### PR TITLE
gui/settings dialog: Add clean all custom config

### PR DESCRIPTION
**Pull request by Croden1999**
# About
- gui/settings dialog: Add clean all custom config
to make it easier to clear all custom config settings.
- gui/trophy collection: Add delete all trophies log info

Please Mr. @Zangetsu38 check this PR.

# Result
image
image

### CODE REVIEW

**Comment by Zangetsu38** [comment]
No can accepte this 😅 need found good solution

**Comment by Croden1999** [comment]
> No can accepte this 😅 need found good solution

u r right, Mr. Zangetsu. i need to take the user's opinion

**Comment by Croden1999** [comment]
sorry, i forgot

**Comment by Zangetsu38** [comment]
Sorry, you have good idea, ré open and just set part for clean custom config 👌

**Comment by Croden1999** [comment]
ready to review

**Pull request merged**
