### PR TITLE
Cast non float in sceGxmSetUniformDataF

### PR DESCRIPTION
**Pull request by sunho**
We should cast to non floats in this function. 

Look how VitaGL does: https://github.com/Rinnegatamante/vitaGL/blob/0d2110ac7b001e1e70688c6450a263b361a2b337/source/vitaGL.c#L1366

### CODE REVIEW

**Review by scribam — APPROVED** [review]
These changes fix Flood-It! which was broken by #886

**Comment by sunho** [comment]
@scribam Can you check if https://github.com/Vita3K/Vita3K/pull/941 fixed the issue in Flood-it? It's surprising to hear this pr fixed regression caused by https://github.com/Vita3K/Vita3K/pull/886.

**Comment by scribam** [comment]
#941 does not fix the issue:

Capture

**Comment by sunho** [comment]
:eyes:

**Review by frangarcj — APPROVED** [review]

**Comment by scribam** [comment]
For some strange reasons, Flood It! is still broken after this merge so my first comment must be wrong.

**Pull request merged**
