### PR TITLE
renderer: Retrieve from texture cache when surface was changed

### PR DESCRIPTION
**Pull request by hiroshiyuri**
I open a new PR with fixes from the last https://github.com/Vita3K/Vita3K/pull/2282

Im not sure yet if this is the correct way to handle it 🤔
Can you to look at it a bit more, please?

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Nol open new pr for that, if you want change code, edit commit and force push

**Comment by Macdu** [comment]
This will still break many games as surfaces can be swizzled.

**Comment by hiroshiyuri** [comment]
> This will still break many games as surfaces can be swizzled.

Thanks for you reply. 👍

There are few games for PS Vita using the Kaleido ADV Workshop engine.
Listed here: https://vndb.org/r?q=&s=title&f=02fwKaleido_0ADV_0Workshop-4opsv

When I have some time, I will look if theres a better way to do this without hurting other games with a swizzled surfaces. 🤔

**Comment by hiroshiyuri** [comment]
> This will still break many games as surfaces can be swizzled.

Now it does not break many games but needs improvement

I have not found a better approach to do this yet 🤔

**Comment by hiroshiyuri** [comment]
All right now 😁

@Macdu sensei, can you review please?

**Comment by Macdu** [comment]
That's still a really bad hack, there is no reason for a swizzle u8u8u8u8 surface not to be sampled as u8u8u8u8. My u8u8u8 PR was to allow this texture to be sampled, you try to do the opposite only in a specific case. 
What you want to do is find a discrepency between the texture you want to sample and the surface to be sampled. Looking only at the parameters of the texture or the surface won't work.

**Comment by hiroshiyuri** [comment]
No bad now but is a hack yet.

It remains to be seen why the need region is being extracted out incorrectly when surface cache was changed. 🤔

**Comment by nishinji** [comment]
On master, it fixed.
image
image

**Comment by hiroshiyuri** [comment]
> On master, it is fixed. 

closed in this PR #2996 maybe

good job! 🤝

**Pull request closed without merging**
