### PR TITLE
GHA: Update release date

### PR DESCRIPTION
**Pull request by qurious-pixel**
Update release date on each new release

### CODE REVIEW

**Comment by qurious-pixel** [comment]
```
Fixes this ↴
```

image

**Comment by Zangetsu38** [comment]
why ?
image

**Comment by qurious-pixel** [comment]
> why ? image

Because it is a PR and not Master build. 

Comment out line 131 to build (as PR).

**Comment by Zangetsu38** [comment]
ah yes i see ok

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
