### PR TITLE
SceAudiodec: add mp3 support

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Oh, just after i ask to @1whatleytay for table to racing 👀

**Comment by Zangetsu38** [comment]
if after you canh look for sceAudiodecCreateDecoderExternal with codec AAC, is monster important for 100 % load video with lle mp4, can also be used with load lle avplayer

**Review by Zangetsu38 — DISMISSED** [review]

**Comment by Zangetsu38** [comment]
Is ready to merge ? works fine for me

**Comment by scribam** [comment]
Should be good now, if there is no regression.

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
