### PR TITLE
Update SDL

### PR DESCRIPTION
**Pull request by frangarcj**

### CODE REVIEW

**Comment by 1whatleytay** [comment]
We gotta make sure it works with older versions of macOS too :)

Also if we're going to update headers, might as well update windows and linux binaries too.

**Comment by frangarcj** [comment]
it's just 2.0.9 for 2.0.10. Code says is for the same mac os version.

The difference is that the binary is code signed.

Can you do Windows or leave it for another pr?

**Comment by VelocityRa** [comment]
Why is this not a submodule again?

**Comment by 1whatleytay** [comment]
I'd be up for making this a submodule :D 
Would make it easy to swap out in the future.

I can do windows when I get home.

**Comment by Zangetsu38** [comment]
you can squash all in one commit, no need few commit for any step ^^, set inside one "remove master sdl for move on external :)

**Comment by VelocityRa** [comment]
It's fine, I'll squash when merging.

**Pull request merged**
