### PR TITLE
BANKAI!

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About
- Current WIP support of PS Vita OS!

! For Testing only.

# Todo
- [ ] Fix detect user app installed
- [ ] Fix live area of Welcom park and psp game (Should probably same issue to user app)
- [x] Fix return to Shell when finish init setup
- [ ] Implement support of install pre install fw (pd0 part with welcom park and bgm of shell)
- [ ] Fix Ime Keyboard works in first try
- [ ] Fix setting app boot
- [ ] Fix no enable focus on icon alone

# Result
- lock screen
image

- home
image

- Live area of content manager
image

-live area of psp game (issue using default template)
image

### CODE REVIEW

**Comment by JJoshua04** [comment]
Can I have a link for it? Like a test link to try the os

**Comment by Joaozin-tech** [comment]
> Can I have a link for it? Like a test link to try the os

pleas build test download now https://github.com/Vita3K/Vita3K/actions/runs/5707835341?pr=2826

**Comment by Croden1999** [comment]
mr. Zangestu PR is so cool, i running devkit fw of psvita os in paf 

image
image
image

**Comment by JJoshua04** [comment]
> 

Would it be possible for me to try it on a android device?

**Comment by Zangetsu38** [comment]
> > 
> 
> Would it be possible for me to try it on a android device?

of course :) 
One days :)

**Comment by jdsuhlmann** [comment]
download link please?

**Comment by ArbestRiAgain** [comment]
> (direct)download link please?

Windows: https://github.com/Vita3K/Vita3K/suites/15015817418/artifacts/857299206

**Comment by Toastyisburning** [comment]
the link to download isn't working, does anyone have one that does work?

**Comment by ArbestRi02** [comment]
The download link is gone

**Comment by Haxorzz** [comment]
the dev must've gone seperate ways from vita 3d

**Comment by Zangetsu38** [comment]
> the dev must've gone seperate ways from vita 3d

No, the current PR is stopped because of a conflict on the master, difficult to resolve

**Comment by Haxorzz** [comment]
> > the dev must've gone seperate ways from vita 3d
> 
> No, the current PR is stopped because of a conflict on the master, difficult to resolve

oh okay, thank you for confirming. is there a way to launch the livearea in current builds of Vita3k?

**Comment by Zangetsu38** [comment]
> > > the dev must've gone seperate ways from vita 3d
> > 
> > 
> > No, the current PR is stopped because of a conflict on the master, difficult to resolve
> 
> oh okay, thank you for confirming. is there a way to launch the livearea in current builds of Vita3k?

Not yet

**Comment by Jun10rStud10s** [comment]
any updates?

**Comment by Zangetsu38** [comment]
> any updates?

Nothing

**Comment by Plasma24** [comment]
> > есть какие-нибудь обновления?
> 
> Ничего

Can you give me a download link for windows?

**Comment by Plasma24** [comment]
Can you give me a link to download the OS for windows?

**Comment by jdramirez165** [comment]
Does the anime theme included with the download?

**Comment by Zangetsu38** [comment]
> Does the anime theme included with the download?

No, this theme is here
https://psvt.ovh/theme.php?id=1603367888

**Comment by EnvixityB02** [comment]
can you put the files in your fork?

**Comment by Zangetsu38** [comment]
> can you put the files in your fork?

What file ?

**Comment by EnvixityB02** [comment]
> > can you put the files in your fork?
> 
> What file ?

the vita3k build where you can run livearea

**Comment by Maximoj529** [comment]
Hello 👋 the download link Is gone in the page https://github.com/Vita3K/Vita3K/actions/runs/5707835341?pr=2826 
Screenshot_20250914_071553

Cloud you please other download link please 🥺🥺🥺 to download PlayStation Vita OS - LiveArea on Vita3K emulator please.

**Comment by Zangetsu38** [comment]
> Hello 👋 the download link Is gone in the page https://github.com/Vita3K/Vita3K/actions/runs/5707835341?pr=2826 Screenshot_20250914_071553
> 
> Cloud you please other download link please 🥺🥺🥺 to download PlayStation Vita OS - LiveArea on Vita3K emulator please.


you need look another pr #3427

**Comment by Maximoj529** [comment]
BANKAI! Bad news this page it's opening it says 404 not found cloud you
find other link 🙏🥺🥺🥺
https://github.com/Vita3K/Vita3K/actions/runs/5707835341?pr=2826
Screenshot_20250914_071553

**Comment by Maximoj529** [comment]
But where's download link for PlayStation Vita OS - LiveArea for my Vita 3k?

**Comment by Maximoj529** [comment]
But why?

**Comment by antoniodesousa** [comment]
OMG are you stupid? **READ** what he said. He already told you several times where you can download it.

**Pull request closed without merging**
