### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by pent0**
I don't have a fancy name no more

The third commit still awaits for conformation from sunho

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@sunho approve if for you is fine :)

**Comment by sunho** [comment]
Was third commit squased?

**Comment by pent0** [comment]
It is the second one now. You can view all on what You like dislike

**Review by sunho — COMMENTED** [review]
Nice catch. Could you also delete https://github.com/Vita3K/Vita3K/blob/59021c37b2e9d2859918c5249a898e474e384d2e/vita3k/kernel/src/sync_primitives.cpp#L566 this line?

It is redundant and might hit our back potentially. (unlocking mutex not owned is UB)

**Review by sunho — APPROVED** [review]

**Comment by pent0** [comment]
> It is redundant and might hit our back potentially. (unlocking mutex not owned is UB)

See commit description

**Comment by sunho** [comment]
Nah nah. I was not talking about the line you added. It's totally legitimate fix there. I was talking about the unlock at the end of function condvar_wait.

**Comment by pent0** [comment]
Wait, I think we should move it into handle_timeout, just for any future occasions.

**Comment by Zangetsu38** [comment]
I merge it now is fine for now

**Comment by Zangetsu38** [comment]
> 
> 
> Nice catch. Could you also delete
> 
> https://github.com/Vita3K/Vita3K/blob/59021c37b2e9d2859918c5249a898e474e384d2e/vita3k/kernel/src/sync_primitives.cpp#L566
> this line?
> 
> It is redundant and might hit our back potentially. (unlocking mutex not owned is UB)

for test i have try delete this line, i get instant crash on all game boot ^^

**Comment by sunho** [comment]
yea I read it again and realized it's actually needed because it calls mutex_lock_impl at the end. (thread_lock doesn't get stack destroyed when calling mutex_lock_impl)

**Pull request merged**
