### PR TITLE
Start init Implement Aac for sceAudioDec

### LINKED ISSUE #805: Implement AAC decoder
Related to https://github.com/Vita3K/Vita3K/issues/508

### PR DESCRIPTION
**Pull request by 1whatleytay**
Fixes #805

Some other things I want to do in this PR:
 - [ ] Set up AVIOContext for HLE sceAvPlayer (for Zangetsu .psarc problem)
 - [ ] Rewrite codec modules so they can reject input/ask for a certain amount of input (to not exhaust es buffers as quickly)
 - [x] Format I suppose

### CODE REVIEW

**Comment by Zangetsu38** [comment]
for psarc issue, i thinks mp4 lole can fix this 🤔

**Comment by 1whatleytay** [comment]
I think you're right, but I figured out how to do it while doing AAC and its a 5 second fix. Might as well do it for HLE.

**Comment by Zangetsu38** [comment]
for code format, why just no run format before create any commit ? no understund here 🤔

**Comment by Zangetsu38** [comment]
you need rebase ^^
and more important need implement is sceAudiodecCreateDecoderExternal
it is used by 99 % game with load lle mp4 or with lle avplayer

**Comment by Zangetsu38** [comment]
@scribam help request for aac codec, current code for this pr no works and get crash, if you can help @1whatleytay  :)

**Comment by sunho** [comment]
@1whatleytay I want to pick this up in near future. Would it be fine for you?

**Comment by 1whatleytay** [comment]
Yep, feel free to take it.

**Comment by pent0** [comment]
I think we can just merge dis first

**Comment by Zangetsu38** [comment]
Yes but juste that no works att all for now, and need rebase fox conflict

**Review by Zangetsu38 — APPROVED** [review]
Rebase, conflict fixed, decode aac disable for moment, keep my hack.
Here is commit ready to merge sujest by bent, works so like master here.
Ready for other dev can look inside it and fix crash.

**Pull request merged**
