### PR TITLE
cmake: Add some Info.plist entries.

### PR DESCRIPTION
**Pull request by MaddTheSane**
This adds a `CFBundleIdentifier` and a `CFBundleName`.

### CODE REVIEW

**Comment by VelocityRa** [comment]
Could you prepend the commit message with:
`cmake:`
?

**Comment by MaddTheSane** [comment]
Done

**Comment by VelocityRa** [comment]
That's the Issue title :)
I meant the commit's name, it matters more because it will remain in our git history.
One way to do it is via `git commit --amend`, change it in the text editor (vim by default) and then `git push -f`.

**Comment by MaddTheSane** [comment]
Ah, will do.

**Comment by VelocityRa** [comment]
Got no macOS experience, so I'd rather not merge it immediately, let's wait for a review from @petmac.

**Pull request merged**
