### PR TITLE
gl/sync_state: fix sync_cull.

### PR DESCRIPTION
**Pull request by Zangetsu38**
- fix or improve render on some game

# Result:
-  Improve body and fix some transparante on Ff10 
image

- fix yellow screen
image

- fix character texture
image

### CODE REVIEW

**Review by pent0 — APPROVED** [review]

**Comment by pent0** [comment]
Zang told me he has tested all and things work fine.

**Comment by frangarcj** [comment]
@pent0 are you sure the condition needs to be removed? Maybe we just had inverted culls. GL_FRONT <---> GL_BACK

**Comment by pent0** [comment]
GXM coordinates vs OpenGL coordinates are inverted. Face that is culled by default is back face, front by default is CCW. So we invert it for GXM.

For the condition yes, it seems when viewport is flipped, the vertex order in GXM is also flipped, and game handle that by itself (by default GXM games dont flip viewport, but 2 games I have seen flip viewport and also flip cull mode by itself, akiba and ff10). Homebrews always not flip viewport so nothing changed.

**Comment by frangarcj** [comment]
understood...

but for clip we have to invert? any idea for the viewport on ffx?

**Comment by Zangetsu38** [comment]
ffx10 is not viewport, is other thingsbefore get menu, this things take full screen, and this things can also get fullscreen depending camera move etc

**Comment by pent0** [comment]
Yes for clip we have to invert the vertex and clipping only, thr cull is handled by game

**Comment by frangarcj** [comment]
thanks to both of us

**Pull request merged**
