### PR TITLE
Hide HostState members to improve compilation time (rebased)

### PR DESCRIPTION
**Pull request by scribam**
PR #590 rebased-ish

### CODE REVIEW

**Comment by sunho** [comment]
Amazing

**Comment by Zangetsu38** [comment]
Mac os 41 min ? 🤔 compare my other pr
image

**Comment by petmac** [comment]
I suspect that's due to ccache.

**Comment by sunho** [comment]
@scribam Can you resolve conflicts? We can see the CI build time again with updated cache.

**Comment by sunho** [comment]
Reading the logs of CI, I can see that ccache is from the master branch (https://github.com/Vita3K/Vita3K/commit/407ea1296ed771202797a10afb42127d42669a50)

**Comment by sunho** [comment]
With ccache, the speed's almost same. (mac build is currently slower even in other pr)
image

**Review by sunho — APPROVED** [review]
I think we should merge this soon. This pr's so big, so we'd need to rebase again if we don't merge.

**Review by VelocityRa — COMMENTED** [review]
No no no.

Why force indirection for every access in all these _extremely_ frequently accessed members?
Cache coherency should be taken into account in decisions that affect so much.

I _very_ much disagree with this, even if it decreases compile times slightly.

**Comment by sunho** [comment]
I was leaning hiding state way because it can achieve encapsulation and improve build time. Hearing velo's perspective about cache, I'm now more in favor of keeping with current way.

**Comment by scribam** [comment]
So let's close this then.

**Pull request closed without merging**
