### PR TITLE
Some small fixes to shader recompiler

### PR DESCRIPTION
**Pull request by pent0**
- Non MAD instructions have their own predicate types (fix Gravity Rush and Oretachi ni Tsubasa wa Nai)
- Correct mask write (for example we want to write a vec2 to r1.x--w, but instead old code write to r1.xy, fix Metal Slug 3 and coconut)
- Implement IMAD8 (fix blazblue no floor)
- Add comparision detection in VTST for integer types

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Result:
- Metal slug 3 and coconut playable
- Gravity Rush
image

**Comment by pent0** [comment]
I will squash and fix wrong things tomorrow

**Review by Zangetsu38 — APPROVED** [review]

**Review by Zangetsu38 — CHANGES_REQUESTED** [review]
Need fix regression on last commit before can merge

**Review by Zangetsu38 — DISMISSED** [review]

**Review by Zangetsu38 — APPROVED** [review]
LGTM

**Comment by pent0** [comment]
Bruh I was sleeping

**Pull request merged**
