### PR TITLE
renderer/gl: Correct viewport formula again

### PR DESCRIPTION
**Pull request by frangarcj**
It need some testers. It works ok for Retroarch

### CODE REVIEW

**Comment by pent0** [comment]
This should only be applied if hardware flip is not enabled.

**Comment by pent0** [comment]
I will look on it so dont merge yet

**Comment by Zangetsu38** [comment]
bad, i_ have already signaled don't merge it, broken render if you enable hardware flip, (yellow screen)

**Comment by VelocityRa** [comment]
You "signaled" to whom?
Post it on the PR next time, can't expect everyone to read everything on the Discord.
I'm reverting it.

**Comment by Zangetsu38** [comment]
yes, i have signaled in discord post after franjir have ask me for test, and i have report this

**Pull request merged**
