### PR TITLE
settings_dialog: Add support cpu backend for custom config.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
- Simply add possibility change cpu backend for custom config.
- remove set value in kernel, value is already set in app init, so no need re set again.

### CODE REVIEW

**Comment by sunho** [comment]
I'll pr a fix to make backend change apply without restarting emu.

**Review by sunho — APPROVED** [review]

**Comment by Zangetsu38** [comment]
> I'll pr a fix to make backend change apply without restarting emu.

Is already possible for me ^^ i can change cpu backend and just run app and ut using it

**Comment by sunho** [comment]
Callback pool is not affected at all. It's going to be quite massy.

**Comment by Zangetsu38** [comment]
> Callback pool is not affected at all. It's going to be quite massy.

Ah yes is what is init on boot but that works without for that

**Comment by sunho** [comment]
So some part is emulated using unicorn while other is emulated usimg dynarmic. It's mixing both of them. I'll deal with it.

**Comment by Zangetsu38** [comment]
> So some part is emulated using unicorn while other is emulated usimg dynarmic. It's mixing both of them. I'll deal with it.

Yes i have get surprised with switch on dynamic and run app with it using it ^^

**Pull request merged**
