### PR TITLE
shader: implement sb_mode in smp

### PR DESCRIPTION
**Pull request by sunho**
# About PR

Stub sb_mode 3.

# Related issue

This fixes black floor glitch in p4g when running vita3k with intel hd gpu.

### CODE REVIEW

**Review by frangarcj — APPROVED** [review]

**Comment by Zangetsu38** [comment]
@poudink can you test this PR with sackboy run for your black texture issue ?

**Comment by poudink** [comment]
My attempts at building this were met with failure because I don't really know what I'm doing. If you have a build then I can test.

**Comment by Ristellise** [comment]
@poudink https://github.com/Vita3K/Vita3K/pull/1006/checks Artifacts has the builds for this PR

**Comment by poudink** [comment]
Fuck I only checked the latest workflow for the PR and that one didn't have artifacts so I thought there weren't any. Well anyway, while does indeed appear to be fixed, RSR is still as broken as before, unfortunately.

**Pull request merged**
