### PR TITLE
[WIP] Implement sceIoGetstatByFd

### PR DESCRIPTION
**Pull request by bentokun**
I uses some ugly black magic, this is a temporary solution until a proper VFS is implemented.
This is not tested on Unix or MacOS yet.

### CODE REVIEW

**Comment by VelocityRa** [comment]
Why not keep paths ourselves in a `std::map` or something, instead of using native APIs?

**Comment by bentokun** [comment]
Yeah, it was dumb of me to do so, waste of time.

**Comment by VelocityRa** [comment]
Can you change the code back to doing that? I'd like to prevent such platform specific code when we can afford it and I think it's a better solution anyway. Thanks.

**Comment by bentokun** [comment]
On my way.

**Comment by bentokun** [comment]
Closing for new PR since my local got ruined by rebase.

**Pull request closed without merging**
