### PR TITLE
modules/SceSysmodule: Implement sceSysmoduleIsLoadedInternal.

### PR DESCRIPTION
**Pull request by Zangetsu38**

### CODE REVIEW

**Comment by bookmist** [comment]
All modules can be checked with this function, not only system. But there are some module flags checks in disasmed code. (is it game program, is it system program, is it development mode)

**Comment by Zangetsu38** [comment]
Is see 🤔

**Comment by Zangetsu38** [comment]
> All modules can be checked with this function, not only system. But there are some module flags checks in disasmed code. (is it game program, is it system program, is it development mode)

Changed, good like this

**Comment by bookmist** [comment]
Good. It would be good to also add check if internal_module_id is valid (-module_id between 0x01 and 0x29)

**Comment by Zangetsu38** [comment]
done

**Review by bookmist — APPROVED** [review]

**Pull request merged**
