### PR TITLE
Improve blending translation and fix font regression 

### PR DESCRIPTION
**Pull request by Zangetsu38**
- Inspired by @scribam and @sunho commit but totaly changed
- based on scriban commit https://github.com/scribam/Vita3K/commit/4ca5c9328dc702dc3895c40f84bafb7d61239712  and refactored for more smart and logical, don't request any if with just using switch present

- fix regression see on  #1059 

# Result: 
image
image

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@scribam request review please

**Comment by scribam** [comment]
@Zangetsu38 The changes from my commit are experimental, I don't know if there are right or wrong, that's why I didn't make a pull request to submit them.
If you haven't noticed a regression with your changes on top of mine, well I guess this code can be merged.

**Comment by Zangetsu38** [comment]
No is perfect for 2d game qnd also for 3d model

**Review by scribam — APPROVED** [review]

**Comment by Zangetsu38** [comment]
@scribam  Thx, can close wip zara pr now

**Pull request merged**
