### PR TITLE
 SceCtrl: misc improvements

### LINKED ISSUE #1055: Analog and L/R button no works on A Rose in the Twilight and Yomawari game
# Issue: 
- [x] Analog no respond, only digital button works, fixed by @scribam on pr #1069                                  
- [x] L/R buttons no works, fixed by @scribam on pr #1069 

# Screenshots:
- Ingame with Analog no works
image

- Manual controller screen
image

# Log
[vita3k.log](https://github.com/Vita3K/Vita3K/files/5724750/vita3k.log)

### PR DESCRIPTION
**Pull request by scribam**
Fix #1055

### CODE REVIEW

**Comment by Zangetsu38** [comment]
good fix analog, but in same time get monster slow down on perfomance, i get 60 on master to 30 on pr 🤔 no idea why get this

**Comment by scribam** [comment]
Can you use latest master to compare performance with this PR ? Yours is the one with 1792 commits, master has 1798 commits.

I have no performance issues:
Capture

Same FPS in master

**Comment by Zangetsu38** [comment]
hmm ok i have no understund, i habe put exe inisde ame folder master and yes speed is same lol so is good :)

**Comment by Zangetsu38** [comment]
update, i have found, relateone module inside automatic mode load lle, i check what odule get speed divide by 2

**Comment by Zangetsu38** [comment]
Update, after search is relate systemgesture lle used by automatic lle mode, disable it get max perf, just no idea why no get this before this commit ^^

**Review by Zangetsu38 — APPROVED** [review]

**Comment by scribam** [comment]
PR updated, the L/R buttons should work now.

**Comment by Zangetsu38** [comment]
strange, L/R no works for me like before

**Comment by Zangetsu38** [comment]
on pause menu you can go on map and options with L/R ? 
image
i am blocked on this level

**Comment by Zangetsu38** [comment]
ok after try with DS4, that full work now but only with so xinput controller
can you check for fix with keyboard input ?

**Comment by Zangetsu38** [comment]
after more play and go level 5, on Xinput only square  no  works, and on keyboard only L/R no works

**Comment by Zangetsu38** [comment]
ah, if L1/R1 lissing that no can works lol, and so for Square on xinput ?

**Comment by scribam** [comment]
I think I found the issue, wait for the fix.

**Comment by Zangetsu38** [comment]
ok thx :)

**Comment by scribam** [comment]
Square button with XInput should be fixed. Try again and let me know.

**Comment by Zangetsu38** [comment]
yes good works, confirmed on Yomawari and A rose all good works, ready to merge 👍

**Review by IllusionMan1212 — APPROVED** [review]

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
