### PR TITLE
vita3K: Bump version to 0.2.0.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About
- Happy new year 2024

### CODE REVIEW

**Comment by nishinji** [comment]
typo of commit name (vitak)

**Comment by Zangetsu38** [comment]
> typo of commit name (vitak)

Oups lol

**Comment by Zangetsu38** [comment]
Done

**Review by Macdu — APPROVED** [review]

**Comment by Zangetsu38** [comment]
Is ready

**Comment by Macdu** [comment]
Yes, I was just waiting to merge croden's PR before this one sorry

**Comment by Zangetsu38** [comment]
I see 👌

**Pull request merged**
