### PR TITLE
app selector: Add app filter by region and by type:

### PR DESCRIPTION
**Pull request by Zangetsu38**
- Can allow application filter by region, for can show only app correspond zone selected

# Result:
- for jap
image

- for commercial only
image

- for hombrew only
image

### CODE REVIEW

**Review by frangarcj — APPROVED** [review]

**Comment by Ristellise** [comment]
> Jap
Personally I'd use Jpn, people mentioned to me before that jap is kinda a degeneratory term.

**Comment by Zangetsu38** [comment]
> 
> 
> > Jap
> 
> Personally I'd use Jpn, as people mentioned to me before that jap is kinda a degeneratory term.

eu ? what ? Jap is just Japanese with using first letter that all 🤔

**Comment by pent0** [comment]
You can type full word Japan

**Comment by Zangetsu38** [comment]
> 
> 
> You can type full word Japan

no, look more, i using only contracfted word for all

**Comment by Zangetsu38** [comment]
> 
> 
> You can type full word Japan

i have write contracted word for other, for used short name 🤔

**Pull request merged**
