### PR TITLE
lang: fix trophy collection language

### PR DESCRIPTION
**Pull request by Croden1999**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Sorry but, i no understund your pr here 🤔

**Comment by Zangetsu38** [comment]
No touch file format and translate, for all translate i using official string

**Comment by Zangetsu38** [comment]
If you have see any error rapport it but i no approuve this, you broken ly format and also broken some child name

**Comment by Croden1999** [comment]
> If you have see any error rapport it but i no approuve this, you broken ly format and also broken some child name

i mean, but the trophy collection dialog does not correspond to the PSVita. Mr. Zangetsu.

image

**Comment by Croden1999** [comment]
so i want change this context

image

**Comment by Croden1999** [comment]
> If you have see any error rapport it but i no approuve this, you broken ly format and also broken some child name

if i make mistake, i am so sorry, sir.

**Comment by Zangetsu38** [comment]
oh is just for this, ok, next time show screen :D but yes touch xml is little hard lol can broken format :D i look on it thx :)

**Comment by Zangetsu38** [comment]
but for info, xml is fine, probleme here is other things :) but thx for this psvita screen

**Comment by Zangetsu38** [comment]
sujestion, go commme on vita3k discord, and contact me, if you have see any other error compare psvita :)

**Comment by Zangetsu38** [comment]
@Croden1999 i have pr my proper stuff with your finded issue :) thx again

**Comment by Croden1999** [comment]
> @Croden1999我已经用你发现的问题公关了我的合适的东西:) 再次
> 感谢，你可以在我的公关上看到，我没有损坏所有的 xml 文件 :D，xml 格式要求特别注意不要损坏它 ^^

okay, i understand, thx a lot, sir.

**Comment by Croden1999** [comment]
> @Croden1999 i have pr my proper stuff with your finded issue :) thx again,
> and you can see on my pr, i no broken all xml file :D, xml format request particular attention for no broken it ^^

okay, i understand, thx a lot, sir.

**Pull request closed without merging**
