### PR TITLE
gui/home screen: Add badge of compat.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
- gui/home screen: Add badge of compat.
Add feature to display icons and compat badges only in visible area.
- compat: small refactor compat db loaded.

# Result
- grid mode
image

- List mode
image

### CODE REVIEW

**Comment by CoffeeBrewer64** [comment]
The colour covering zen pinball 2 isn't the right colour, it's more of a pinky red instead of a red.

**Comment by Zangetsu38** [comment]
> The colour covering zen pinball 2 isn't the right colour, it's more of a pinky red instead of a red.

Color is currently in discussion

**Comment by Croden1999** [comment]
if used grid mode, could u add checkbox to show/hide them, sir?

**Comment by Zangetsu38** [comment]
> if used grid mode, could u add checkbox to show/hide them, sir?

For why ?

**Comment by Croden1999** [comment]
> > if used grid mode, could u add checkbox to show/hide them, sir?
> 
> For why ?

make the image show full and diversity.

**Review by Macdu — APPROVED** [review]

**Pull request merged**
