### PR TITLE
cmake: some refactor and set on link time optimization

### PR DESCRIPTION
**Pull request by bookmist**
This changes were inspired by this https://github.com/Vita3K/Vita3K/issues/1418#issuecomment-1267773600 comment

I'm not sure if link time optimization is worth it, but it seems to have no problems.

### CODE REVIEW

**Comment by Macdu** [comment]
Nice PR, I would advise LTO to be enabled only for the release build (`if(CMAKE_BUILD_TYPE STREQUAL "Release")`) as it increases in a non-negligible way the compile time even when modifying only one file.

**Comment by bookmist** [comment]
@Macdu ready for review.
I hope it will compile faster after first rebuild.
cmake variable for link time optimization supports 3 values: ALWAYS RELEASE_ONLY NEVER default value is RELEASE_ONLY

boost builds with LTO for modes ALWAYS and RELEASE_ONLY. I think it's not a problem to make non-LTO build with LTO static libraries. It's not an easy way to force rebuild boost in current environment, so this will be checked sometimes in future by a new developer.

**Comment by Macdu** [comment]
> boost builds with LTO for modes ALWAYS and RELEASE_ONLY. I think it's not a problem to make non-LTO build with LTO static libraries. It's not an easy way to force rebuild boost in current environment, so this will be checked sometimes in future by a new developer.

Actually it is a problem, you can use non-lto libs in a lto project but not the opposite. The linker should crash if you were to try that.
The github CI does not use the boost executable (it uses boost from vcpkg instead), so I think you can make the boost build non-lto, it should be fine from my point of view (gcc also has the flag `-ffat-lto-objects` to build a lib containing both the lto and non-lto code), but if you are another idea you can try it.

**Comment by Macdu** [comment]
Also one think that could be done (in another PR I guess) would be for the C++ packages used by the github CI to be built with LTO. I believe this is easily doable.

**Comment by bookmist** [comment]
> Actually it is a problem, you can use non-lto libs in a lto project but not the opposite. The linker should crash if you were to try that. The github CI does not use the boost executable (it uses boost from vcpkg instead), so I think you can make the boost build non-lto, it should be fine from my point of view (gcc also has the flag `-ffat-lto-objects` to build a lib containing both the lto and non-lto code), but if you are another idea you can try it.

@Macdu I make the boost build non-lto. Now it's ready for review.

**Review by Macdu — APPROVED** [review]
If you want you can (in another PR) easily configure vcpkg to build LTO versions of the librairies.

**Pull request merged**
