### PR TITLE
Add sceIoGetstat, sceIoDopen, sceIoDread, sceIoDclose

### LINKED ISSUE #16: Doom Wads not showing
How do I run home-brews?
screenshot 139
screenshot 140

### PR DESCRIPTION
**Pull request by Ghabry**
Very basic implementation.

Fix #16

### CODE REVIEW

**Comment by VelocityRa** [comment]
Nice! Since dirent is an [external](https://github.com/tronkko/dirent/blob/master/include/dirent.h) dependency, _maybe_ it should be added in `external/` as a submodule?

**Comment by Ghabry** [comment]
possible... But have to read a guide about adding submodules first because I love them so much and always try to avoid them ^^.

**Comment by Ghabry** [comment]
Proof

captura

**Comment by petmac** [comment]
I hope I got the merge right.

**Comment by Zangetsu38** [comment]
need rebase and squach for fix conflict with master

**Comment by Ghabry** [comment]
rebased on upstream, hope it compiles ^^'

**Pull request merged**
