### PR TITLE
gui/live_area: Add lang strings to the help dialog

### PR DESCRIPTION
**Pull request by Croden1999**
add some lang strings to the livearea/help dialog, add lang can help some users to know about these controls. plz Mr. @Zangetsu38 check this PR. 

- not install fw
image

- installed fw
image

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Not good, is not help, is juste control of live area screen only

**Comment by Croden1999** [comment]
> Not good, is not help, is juste control of live area screen only

but even if it's not important, and adding a language helps some users, also i not touch livearea button

**Comment by Zangetsu38** [comment]
> > Not good, is not help, is juste control of live area screen only
> 
> but even if it's not important, add lang can help some users, also i not touch livearea button, Mr. Zangetsu

Sorry, bad explain, i have just said is no help, but live area/help lol

**Comment by Zangetsu38** [comment]
is not help dialog, but just help inside live area, so create child inside live_area and create help child and put juste inside, code is fine, juste move inside other child, help dialog is wrong

**Comment by Croden1999** [comment]
> is not help dialog, but just help inside live area, so create child inside live_area and create help child and put juste inside, code is fine, juste move inside other child, help dialog is wrong

i got it, thx again, sir.

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
