### PR TITLE
Add features.yml to fine-tune shader recompilation command

### PR DESCRIPTION
**Pull request by sunho**
# About PR

- Dump graphic engine features as yaml file
- Add cli that can compile dumped gxp program configured by dumped features.yml

# With this PR

1. We can debug the shader recompilation easily. 
2. We can easily build the automated shader recompilation tests that might help us fight regression.

### CODE REVIEW

**Comment by 1whatleytay** [comment]
What about the `-s` option?

**Comment by sunho** [comment]
-s option?

**Comment by 1whatleytay** [comment]
https://github.com/Vita3K/Vita3K/blob/master/vita3k/config/src/config.cpp#L146

This arguments compiles and dumps shader info to log :D 
I'm not entirely sure what's different :3, the features.yml stuff?

**Comment by sunho** [comment]
Oh we already have it. I guess I can make "-s" to use features.yml.

**Comment by sunho** [comment]
I feel like we're not going to test recompiler for next 3 years.

**Pull request closed without merging**
