### PR TITLE
shader: Implement the shader store operation

### PR DESCRIPTION
**Pull request by Macdu**
Implement the shader store operation, which is used by shaders to modify the content of buffers.
This obviously only works with memory mapping enabled, as without it, shaders only have access to a copy of the buffer that gets recreated every draw.

This fixes games using this features, mainly 3D Unity games.
However, only half of them are fixed as we still don't implement properly the repeat count for shader stores. This is a bit harder than I thought it would be to reverse engineer, so I will do it in another PR.

### CODE REVIEW

**Review by Zangetsu38 — DISMISSED** [review]

**Comment by Macdu** [comment]
This requires some testing before merging.

**Comment by Zangetsu38** [comment]
Request rebase a’d fix conflict

**Comment by ArbestRiAgain** [comment]
Any more info? Hello?

**Comment by Zangetsu38** [comment]
GOD, please rebase 😭, this all conflict everywhere

**Comment by Macdu** [comment]
I rebased, I just need to adapt some of my code to the modifications I made for shader interlock and macrotile emulation before pushing again.

**Comment by Zangetsu38** [comment]
> I rebased, I just need to adapt some of my code to the modifications I made for shader interlock and macrotile emulation before pushing again.

I see, i speak current conflict on pr here, because yes, master have get very lot change lol

**Review by Zangetsu38 — APPROVED** [review]

**Review by Zangetsu38 — CHANGES_REQUESTED** [review]
need remove f commit here

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
