### PR TITLE
fix a few incorrect strings

### PR DESCRIPTION
**Pull request by nn9dev**
messed up the last PR. this should make a few things easier to read.

### CODE REVIEW

**Comment by nn9dev** [comment]
still learning git.... will put that fix in a different pr....

**Comment by Zangetsu38** [comment]
Ugh...

**Comment by Zangetsu38** [comment]
You need using gut reset hard on first commit hetr

**Review by CoffeeBrewer64 — DISMISSED** [review]
Summary for future reference: typo fix.

looks good to me

**Comment by nn9dev** [comment]
@Zangetsu38 finally i have learned git and fixed this PR. please review to see if anything is wrong.

**Review by Zangetsu38 — DISMISSED** [review]

**Comment by Zangetsu38** [comment]
ah, you need rebase heren, you have conflict 
using git rebase -v vita3K/master
you need adsd url before and fetch

**Comment by nn9dev** [comment]
hopefully should have fixed conflict.

**Comment by Zangetsu38** [comment]
You need rebase and fix conflict

**Comment by Zangetsu38** [comment]
Outdated

**Pull request closed without merging**
