### PR TITLE
lang: Update language.

### PR DESCRIPTION
**Pull request by HuanJiCanShang**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@Croden1999 🙏

**Comment by Croden1999** [comment]
> @Croden1999 🙏

Mr. @Zangetsu38 can merge it

**Review by Croden1999 — APPROVED** [review]

**Comment by Zangetsu38** [comment]
@Croden1999 look last change

**Comment by Croden1999** [comment]
> @Croden1999 look last change

it good for me

**Review by Croden1999 — APPROVED** [review]

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
