### PR TITLE
gui/lang: Correct and improve the format.

### PR DESCRIPTION
**Pull request by Croden1999**
Correct and improve the format of the xml files, also add the "Delete All"(Delete All Trophy) button in Trophy Collection, plz Mr. @Zangetsu38 check this pr.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
this buttoçn no exist on vita 🤔

**Comment by Croden1999** [comment]
> this buttoçn no exist on vita 🤔

but here exist in devkit/testkit.

**Comment by Zangetsu38** [comment]
i see you have screenshot for this ?

**Comment by Zangetsu38** [comment]
also screenshot on code result here

**Comment by Croden1999** [comment]
> i see you have screenshot for this ?

yes, wait a minute, i upload this.

**Comment by Zangetsu38** [comment]
ah yes oki lol

**Review by Zangetsu38 — APPROVED** [review]

**Comment by Croden1999** [comment]
> ah yes oki lol

thx again, sir.

**Pull request merged**
