### PR TITLE
Replace Some Assert With Possible Fix 

### PR DESCRIPTION
**Pull request by Co2333**
nothing much just replaced some assert that may be able to fix at runtime like surface buffer if we alloc them when they don't exist.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Lot need change, you need squash this 3 commit on one, and need run clang format script

**Comment by Co2333** [comment]
okay wait a min

**Comment by Zangetsu38** [comment]
Don't need close pr, just squash all and force push

**Comment by Co2333** [comment]
after a force push, it is not possible to just reopen it but recreate one xD

**Comment by Zangetsu38** [comment]
Yes for that no close pr just force push

**Pull request closed without merging**
