### PR TITLE
Added implementations of sceMt19937 functions

### PR DESCRIPTION
**Pull request by bentokun**
Implement:
- sceMt19937Init
- sceMt19937UInt

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Sadly this module is useless to implement since that library is statically linked in the executable.

After that PR get merged, we should update vita-headers submodule in order to get rid of all those modules: https://github.com/vitasdk/vita-headers/pull/295

**Comment by VelocityRa** [comment]
Thanks for the contribution though @bentokun, I recommend hanging around/asking devs on Discord, before implementing something like this (or most things really, if you're new to the project).

**Comment by Zangetsu38** [comment]
You can Squash your PR for have only one commit, more propr 👍

**Comment by petmac** [comment]
Sorry @bentokun it looks like we don't need this. It's probably worth noting too that C++11 (we require C++14) has Mersenne Twister in the standard library:

http://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine

**Pull request closed without merging**
