### PR TITLE
renderer: Correct front and back disabled value.

### PR DESCRIPTION
**Pull request by Zangetsu38**

### CODE REVIEW

**Comment by sunho** [comment]
This is going to discard the depth. Does this not regress asphalt?

**Comment by sunho** [comment]
It's messy tho, proper fix is just write previous color in glsl.

**Comment by pent0** [comment]
Yes as I say before, why did you forget so fast :(

**Comment by sunho** [comment]
Ah didn't saw it was your commit.

**Comment by hobyst** [comment]
I've tested the commit and it doesn't fix the issue, at least not in PlayStation Vita Pets.

**Comment by Zangetsu38** [comment]
> I've tested the commit and it doesn't fix the background blinking issue, at least not in PlayStation Vita Pets.

normal, request also my pr of #1523 , dbz have same, it very flashing without it, with get litterally black screen

**Comment by Zangetsu38** [comment]
hmmm, to myserious for this

**Pull request closed without merging**
