### PR TITLE
codec & ngs: Implement playback rate scaling

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
Implement playback rate scaling

### CODE REVIEW

**Comment by hobyst** [comment]
Don't pull it. It isn't ready to pull yet.

**Comment by Zangetsu38** [comment]
> Don't pull it. It isn't ready to pull yet.

i know, is for remplace my shit hack, waiting finished stuff off course :)

**Comment by Zangetsu38** [comment]
is now ready for review

**Comment by hobyst** [comment]
> is now ready for review

No, it isn't yet. I still have to revise and test a few more things.

**Comment by hobyst** [comment]
Code should now be ready to review and merge.

**Comment by hobyst** [comment]
Code is now ready to merge.

**Review by frangarcj — APPROVED** [review]

**Pull request merged**
