### PR TITLE
live area: refactor user lang variable.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
for fix ch/zh used in live area template, have different name compare translate gui.

thx to @sunho & @pent0 for some help :)

### CODE REVIEW

**Comment by Croden1999** [comment]
> # About:
> for fix ch/zh used in live area tamplate, have diverent name compare translate gui.
> 
> thx to @sunho & @pent0 for some help :)

hi, Mr.Zangetsu. the ct/zh string has been transposed. thx again.

**Comment by Zangetsu38** [comment]
> 
> 
> > # About:
> > for fix ch/zh used in live area tamplate, have diverent name compare translate gui.
> > thx to @sunho & @pent0 for some help :)
> 
> hello, Mr.Zangetsu. the zh-s/zh-t strings has been switched.
> actually,
> CHINESE_S: zh-s = zh,
> CHINESE_T: zh-t = ch.
> 
> thx Mr. Zangetsu again for this pr.

you are sur ?
cc @pent0

**Comment by Zangetsu38** [comment]
oups :D

**Comment by Zangetsu38** [comment]
> 
> 
> > # About:
> > for fix ch/zh used in live area tamplate, have diverent name compare translate gui.
> > thx to @sunho & @pent0 for some help :)
> 
> hello, Mr.Zangetsu. the zh-s/zh-t strings has been switched.
> actually,
> CHINESE_S: zh-s = zh,
> CHINESE_T: zh-t = ch.
> 
> thx Mr. Zangetsu again for this pr.

Sorry, is fixed lol, i have mistake  during rewrite and copy past

**Comment by Zangetsu38** [comment]
@Croden1999 for other things i need you
image
is for "emulator", in Simplified, it get ? because is probably traditionel string, if you can check inside zh-s in debut part for menubar thx

**Comment by Croden1999** [comment]
> @Croden1999 for other things i need you
> image
> is for "emulator", in Simplified, it get ? because is probably traditionel string, if you can check inside zh-s in debut part for menubar thx

yes, never mind, we install the PUP firmware and then switch language.

**Comment by Croden1999** [comment]
Due to the limitation of TTF font files, there are many simplified characters that show question marks.

**Comment by Zangetsu38** [comment]
> Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.

No relate ttf, issue is relate glyph want said is not simplified

**Comment by Croden1999** [comment]
> > Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.
> 
> No relate ttf, issue is relate glyph want said is not simplified

we need to check the Asis Region option to display jp/ko/zh/ch normal text.

**Comment by Zangetsu38** [comment]
> > > Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.
> > 
> > 
> > No relate ttf, issue is relate glyph want said is not simplified
> 
> we need to check the Asia Region option to display jp/ko/zh/ch normal fonts. psvita will also change fonts when switching system languages.
> 
> in psvita,
> zh/ch load cn0.pvf
> ko load kr0.pvf
> jp load jpn0.pvf
> 
> image

I know that my code and currz t master already done this

**Comment by Croden1999** [comment]
> > > > Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.
> > > 
> > > 
> > > No relate ttf, issue is relate glyph want said is not simplified
> > 
> > 
> > we need to check the Asia Region option to display jp/ko/zh/ch normal fonts. psvita will also change fonts when switching system languages.
> > in psvita,
> > zh/ch load cn0.pvf
> > ko load kr0.pvf
> > jp load jpn0.pvf
> > image
> 
> I know that my code and currz t master already done this.
> If you enable asia région it load traditionel + korean, so fix Word is normal

@Zangetsu38, thx a lot, sir. XD

**Comment by Zangetsu38** [comment]
> > > > > Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.
> > > > 
> > > > 
> > > > No relate ttf, issue is relate glyph want said is not simplified
> > > 
> > > 
> > > we need to check the Asia Region option to display jp/ko/zh/ch normal fonts. psvita will also change fonts when switching system languages.
> > > in psvita,
> > > zh/ch load cn0.pvf
> > > ko load kr0.pvf
> > > jp load jpn0.pvf
> > > image
> > 
> > 
> > I know that my code and currz t master already done this.
> > If you enable asia région it load traditionel + korean, so fix Word is normal
> 
> @Zangetsu38, thx a lot, sir. XD
> 
> if could replace all font formats when switching system language, maybe able to display normal fonts without checking the Asia Region option.

My code alrady to this, it using diferent glyph if is simplified or traditionnelle, so for me here problème is caused by wrong character if this character is showed only in asia région enable want said is traditionnelle and no simplified

**Comment by Croden1999** [comment]
> > > > > > Mr. @Zangetsu38, due to the limitation of ttf font file, there are many simplified and traditional characters that show question marks. maybe it's not the ttf font file question.
> > > > > 
> > > > > 
> > > > > No relate ttf, issue is relate glyph want said is not simplified
> > > > 
> > > > 
> > > > we need to check the Asia Region option to display jp/ko/zh/ch normal fonts. psvita will also change fonts when switching system languages.
> > > > in psvita,
> > > > zh/ch load cn0.pvf
> > > > ko load kr0.pvf
> > > > jp load jpn0.pvf
> > > > image
> > > 
> > > 
> > > I know that my code and currz t master already done this.
> > > If you enable asia région it load traditionel + korean, so fix Word is normal
> > 
> > 
> > @Zangetsu38, thx a lot, sir. XD
> > if could replace all font formats when switching system language, maybe able to display normal fonts without checking the Asia Region option.
> 
> My code alrady to this, it using diferent glyph if is simplified or traditionnelle, so for me here problème is caused by wrong character if this character is showed only in asia région enable want said is traditionnelle and no simplified

i see, thank u, sir.

**Review by IllusionMan1212 — APPROVED** [review]
looks good

**Pull request merged**
