### PR TITLE
Update zh-s.xml

### PR DESCRIPTION
**Pull request by Enaium**

### CODE REVIEW

**Review by Zangetsu38 — DISMISSED** [review]

**Comment by Croden1999** [comment]
please do not change it, just keep it English. 请不要更改它，让它保持英文。

**Comment by Enaium** [comment]
> please do not change it, just keep it English, because if not install font firmware package, there are not display normal font for Chinese, and also the Initial Setup not based on psvita lang.
> 请不要更改它，让它保持英文，因为如果未安装字体固件包，中文字体是不会正常显示的，而且初始设置不是基于psvita中的语言。

ok

**Comment by Croden1999** [comment]
> > please do not change it, just keep it English, because if not install font firmware package, there are not display normal font for Chinese, and also the Initial Setup not based on psvita lang.
> > 请不要更改它，让它保持英文，因为如果未安装字体固件包，中文字体是不会正常显示的，而且初始设置不是基于psvita中的语言。
> 
> ok

thanks so much.
非常感谢。

**Comment by Croden1999** [comment]
> > please do not change it, just keep it English, because if not install font firmware package, there are not display normal font for Chinese, and also the Initial Setup not based on psvita lang.
> > 请不要更改它，让它保持英文，因为如果未安装字体固件包，中文字体是不会正常显示的，而且初始设置不是基于psvita中的语言。
> 
> ok

thanks so much.
非常感谢。

**Comment by Zangetsu38** [comment]
Yes sorry, ch is very special, and works only in font package installed

**Pull request closed without merging**
