### PR TITLE
gui/lang: Improve and update some lang strings

### PR DESCRIPTION
**Pull request by Croden1999**
# About
- update lang strings for app context menu (compatibility and options for other languages) , initial setup (only in install firmware, can help users to easy install firmware) and welcome dialog.
- improve lang strings in Install Dialog to looks more specification (but reinstall dialog only running on OpenGL, not display on Vulkan).
- add lang strings in Performance Overlay.

# Result
image
image
image
image
image
image

### CODE REVIEW

**Comment by Croden1999** [comment]
i need some time to finish this pr, so i changed to draft.

**Comment by Croden1999** [comment]
please Mr. @Zangetsu38 review this pr, i am ready.

**Comment by Zangetsu38** [comment]
need rebase and fix conflict

**Comment by Croden1999** [comment]
> need rebase and fix conflict

got it.

**Comment by Croden1999** [comment]
plz check it again, sir. :) @Zangetsu38

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
