### PR TITLE
gui/lang: Add small_mday and improve the date format.

### PR DESCRIPTION
**Pull request by Croden1999**
- add small_days and improve the date format, e.g. de, es and pt-br, to same like psvita.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
I need explain, what is small days ? 🤔

**Comment by Croden1999** [comment]
> I need explain, what is small days ? 🤔

wait a minute, i take my psvita photo.

**Comment by Croden1999** [comment]
- de


- es, pt-br

**Comment by Croden1999** [comment]
because de has a punctuation mark, if not adding small_days breaks the date format, Mr. @Zangetsu38 .

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
