### PR TITLE
Update version of SPIRV-Cross and glslang

### PR DESCRIPTION
**Pull request by bookmist**
It looks like we update dependencies, so why not to update glslang and SPIRV-Cross.

It's not the last version of glslang, but it's last version I can make working here.

Changes are precision, discard and spirv-version (if version is newer, then spirv-cross does not emit global variables)

### CODE REVIEW

**Comment by sunho** [comment]
I feel hesitatant to update spir-v cross, as we're using it in a non standard way. It's easy to regress as spriv cross author works on it to improve standard use case. (disassemble glsl compiler output) We're not really akeen to the spir-v cross internals, so regression on spir-v level can be frustrating.

**Review by scribam — DISMISSED** [review]
Looks fine to me, the branch has a conflicting file though.
As sunho said, regression can happen but Vita3K is still an experimental emulator🙂

**Comment by Zangetsu38** [comment]
need fix conflict here

**Comment by bookmist** [comment]
conflict fixed, rebased to master
@scribam thank you very much for your attention to this PR

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
