### PR TITLE
ci: Set clang as default compiler for Ubuntu

### PR DESCRIPTION
**Pull request by scribam**
Fix issue #1182 but discord integration has to be disabled to prevent a compilation issue with clang.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
I am not sur Disable discord is needed 🤔

**Comment by scribam** [comment]
Check yourself https://github.com/scribam/Vita3K/runs/2125554562. Same changes as this one but without `-DUSE_DISCORD_RICH_PRESENCE=OFF`

**Comment by Zangetsu38** [comment]
> 
> 
> Check yourself https://github.com/scribam/Vita3K/runs/2125554562. Same changes as this one but without `-DUSE_DISCORD_RICH_PRESENCE=OFF`

i see

**Comment by Zangetsu38** [comment]
is not fixed for now 🤔  build contintinue stop procces durring long time on ubuntu

**Comment by Zangetsu38** [comment]
CodeQL have again take 1h, no fix issue :/

**Comment by scribam** [comment]
2m after a rerun, thanks to the cache.

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
