### PR TITLE
modules/SceNet: scenetEpoll* functions and sockopts

### PR DESCRIPTION
**Pull request by edwinr**
Implement and improve some of the network functions. Improves compatibility with homebrew built using vitasdk that use `select`. This also includes those that use libcurl such as this sample program: https://github.com/vitasdk/samples/tree/master/net_libcurl

- Implement `sceNetEpollControl`
- Implement `sceNetEpollCreate`
- Implement `sceNetEpollDestroy`
- Implement `sceNetEpollWait`
- Implement `sceNetGetsockopt`
- Improve `sceNetSetsockopt` implementation

### CODE REVIEW

**Comment by Zangetsu38** [comment]
you need run format,squash commit, and name commit correctly

**Comment by edwinr** [comment]
@Zangetsu38 is the squashed commit named correctly now?
I will still need to look into failing build on Ubuntu

**Comment by Zangetsu38** [comment]
> @Zangetsu38 is the squashed commit named correctly now? I will still need to look into failing build on Ubuntu

is fine yes, after, juste using edit last commit and force push

**Review by Macdu — APPROVED** [review]
lgtm

**Pull request merged**
