### PR TITLE
Revert "Add Unicorn as an external project"

### PR DESCRIPTION
**Pull request by petmac**
Reverts Vita3K/Vita3K#277

Crashes on Windows were reported via Discord, so let's revert this and test some more on Windows.

### CODE REVIEW

**Comment by VelocityRa** [comment]
I don't think there's a need for this. It should just be fixed in a future commit, no reverts.

**Comment by d3m3vilurr** [comment]
I also same opinion as @VelocityRa don't need revert, just need fix windows build.

**Comment by muemart** [comment]
Found a solution to fix the crashes. The trick is to add `/guard:cf ` as a switch to the compiler. Though it's a bit of a pain to add it in the CMake file, because I can't find a way to set compiler flags with the msbuild command. Any ideas?

**Comment by VelocityRa** [comment]
Apparently the issue happens on the first `svc` instruction, when (before?) the relevant unicorn hook gets called.
Thanks @muemart, I did try it for the `emulator` and `cpu` project but it didn't work, I'm guessing it's needed for all the projects?

In any case, it [looks like](https://msdn.microsoft.com/en-us/library/dn919635.aspx) this has runtime overhead, so maybe we should find a better fix for this. Any ideas?

**Comment by muemart** [comment]
The flag doesn't need to be set for the Vita3K projects, but when compiling unicorn. Sorry if that wasn't clear. Unicorn crashes when calling longjmp (but not every call...), and I found this similar issue [here](https://developercommunity.visualstudio.com/content/problem/115305/longjmp-incompatible-with-guardcf.html) which brought me to that switch. Not sure if there's another fix, but I'm not really sure why that flag fixes the crashes either.

**Comment by muemart** [comment]
After even more trial and error, I found a way to make it work.
Unicorn: Compile with `/Zi` instead of `/ZI`
Vita3K: Disable inlining (`/Ob0`) for cpu, kernel, and modules. In thread.cpp, add a `try{}catch(...){}` around the code inside the call_svc lambda.
I wonder if disabling inlining is too big of a performance hit.

**Comment by VelocityRa** [comment]
Thank you for looking into this more @muemart, but these workarounds are definitely not acceptable. I looked into the issue too as well as using clang instead on Windows yesterday (you can read #development scrollback on our Discord), but no dice.

So, looks like we're gonna have to revert this, it's been a week since master is broken on Windows.

**Comment by petmac** [comment]
Maybe we should accelerate our looking at #68, but I'm aware there's work to be done on Dynarmic itself for that to happen.

**Comment by VelocityRa** [comment]
Not a bad idea... I can try and talk with Mary again, see if anything has changed with ARM-v7 progress.
Although I've been sorta keeping up with its development and I haven't seen much that _directly_ affects us.
I'll look into it.

**Comment by muemart** [comment]
I assume this is a compiler bug, so I'm thinking about opening an issue for MSVC, though I haven't managed to do a minimal repro of the crash.
In the mean time, reverting is probably the best idea unless there's a replacement ready.

**Pull request merged**
