### PR TITLE
modules/SceFiber: implement _sceFiberAttachContextAnd(Run/switch)

### PR DESCRIPTION
**Pull request by Zangetsu38**
credit code by @sunho, with other dev i thinks it works fine with all app using it, and can good merged on master, add note inside if more check is needed later

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@sunho if you want i change any things, but this code very request on master here.

**Comment by sunho** [comment]
It should be better than nothing. Just add STUBBED.

**Comment by Zangetsu38** [comment]
> 
> 
> It should be better than nothing. Just add STUBBED.

i add particulary message in stubb ?

**Comment by Zangetsu38** [comment]
@sunho i have add stubbed message

**Review by frangarcj — APPROVED** [review]

**Pull request merged**
