### PR TITLE
modules/SceGxm: Implement RenderTargetGetDriverMemBlock.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
- Implement sceGxmRenderTargetGetDriverMemBlock.
- should fix crash on some game.

# Result
get ingame for Senran kagura/to love ru battle ectasy and more

### CODE REVIEW

**Comment by Zangetsu38** [comment]
is stub code by @bookmist, i waiting @pent0 can check it for maybe proper implement

**Comment by pent0** [comment]
Store driverMemBlock from params struct in init function to SceGxmRenderTarget. And in this function get that variable. Is there any problem hindering it?

**Comment by Zangetsu38** [comment]
> 

i already know all of this, i have show you this in dm, i know, just what is function init for get this value and what is this value inside this function ? 🤔

**Comment by Zangetsu38** [comment]
> Store driverMemBlock from params struct in init function to SceGxmRenderTarget. And in this function get that variable. Is there any problem hindering it?

done 👌

**Review by pent0 — APPROVED** [review]
Nice!

**Pull request merged**
