### PR TITLE
 Fixed gramatical errors, merged Linux and Windows build directory names, simplified .gitignore

### PR DESCRIPTION
**Pull request by xero-lib**
Updated the `lang` files with proper English, and modified the `gen-windows.bat` script to build to the proper directory name, `build`. Removed superfluous `.gitignore` entries.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
wjhy 3 commit ?

**Comment by Zangetsu38** [comment]
split your pr in 2 commit for lang fix/bash change

**Comment by Zangetsu38** [comment]
and no close for re open new pr, change your commit, and force push, learn how ujsing git

**Comment by xero-lib** [comment]
How do I split a pr into two commits? I'd have to basically rewrite history. It ends up with the same result either way, I mean I'll try but I don't get the fuss.

**Comment by Zangetsu38** [comment]
you very need learn how using git here

**Comment by xero-lib** [comment]
I'm not gonna go through deleting commits, I'm just going to refork and repull. I'm sorry you want it in the same PR, but it'll end up with the same result.

**Comment by Zangetsu38** [comment]
NO, you have already open 2 PR for this, stop

**Comment by xero-lib** [comment]
So you want me to rewrite the history instead of just redoing it?

**Comment by Zangetsu38** [comment]
i have done it, is very easy, no need rewrite histoiry, just learn git that all

**Comment by xero-lib** [comment]
If it's very easy, please tell me how to do it, or link me to a reference.

**Comment by Zangetsu38** [comment]
take it, and force push on this branch
https://github.com/Zangetsu38/Vita3K/commits/lang

**Comment by xero-lib** [comment]
I already deleted the fork also.

**Comment by xero-lib** [comment]
I can't push to your repo

**Comment by Zangetsu38** [comment]
WHAt ? i said take my branch, and force push on YOUR master branch

**Pull request closed without merging**
