### PR TITLE
lang: Update language strings

### PR DESCRIPTION
**Pull request by Croden1999**
To looks more reasonable.

image
image

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Remove the "comp", it's short for Compatibility
so there is no possible translation in itself
but is good for other

**Comment by Croden1999** [comment]
> Remove the "comp", it's short for Compatibility so there is no possible translation in itself but is good for other

okay, i got it.

**Comment by Zangetsu38** [comment]
> > Remove the "comp", it's short for Compatibility so there is no possible translation in itself but is good for other
> 
> okay, i got it. Of course, i knew the "comp" is short for compatibility, maybe it is good for a small amount of text, like of jp/ch/zh
> 
> image

hmm is writed what like word here ? for comp ?

**Comment by Croden1999** [comment]
> > > Remove the "comp", it's short for Compatibility so there is no possible translation in itself but is good for other
> > 
> > 
> > okay, i got it. Of course, i knew the "comp" is short for compatibility, maybe it is good for a small amount of text, like of jp/ch/zh
> > image
> 
> hmm is writed what like word here ? for comp ?

yes, the "compatibility" in Simplified Chinese is "兼容性"

**Comment by Zangetsu38** [comment]
hmm oki i see

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
