### PR TITLE
external, vita3k: Update dynarmic and add initial support for aarch64

### PR DESCRIPTION
**Pull request by Macdu**
Backport some of the changes I made for the android version to the PC version.
With these changes, adding support for arm64 Linux, Macos and/or Windows should be quite straightforward. 

A lot of the content of this PR is similar to what @KhoraLee did in #2166.

### CODE REVIEW

**Comment by cobalt2727** [comment]
```cpp
In file included from /home/ubuntu/Vita3K/external/unicorn/qemu/cputlb.c:22:
/home/ubuntu/Vita3K/external/unicorn/qemu/include/config.h:1:10: fatal error: 'config-host.h' file not found
#include "config-host.h"
         ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by cobalt2727** [comment]
text wall incoming, apologies in advance:

```bash
cobalt@pi4b:~/Vita3K$ cmake --build build/linux-ninja-clang/
[0/2] Re-checking globbed directories...
[5/229] Building CXX object vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibc/SceLibc.cpp.o
FAILED: vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibc/SceLibc.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DBETTER_ENUMS_STRICT_CONVERSION=1 -DBOOST_ALL_NO_LIB -DONLY_MSPACES=1 -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_NO_THREAD_ID -DTRACY_ENABLE -DTRACY_NO_SYSTEM_TRACING -DTRACY_ON_DEMAND -DUSE_LOCK=0 -DCMAKE_INTDIR=\"Debug\" -I/home/cobalt/Vita3K/build/linux-ninja-clang/vita3k/config -I/home/cobalt/Vita3K/vita3k/modules/include -I/home/cobalt/Vita3K/vita3k/audio/include -I/usr/include/SDL2 -I/home/cobalt/Vita3K/vita3k/codec/include -I/home/cobalt/Vita3K/vita3k/ctrl/include -I/home/cobalt/Vita3K/vita3k/emuenv/include -I/home/cobalt/Vita3K/vita3k/mem/include -I/home/cobalt/Vita3K/vita3k/util/include -I/home/cobalt/Vita3K/vita3k/config/include -I/home/cobalt/Vita3K/vita3k/np/include -I/home/cobalt/Vita3K/external/yaml-cpp/include -I/home/cobalt/Vita3K/external/fmt/include -I/home/cobalt/Vita3K/external/spdlog/include -I/home/cobalt/Vita3K/vita3k/http/include -I/home/cobalt/Vita3K/vita3k/dialog/include -I/home/cobalt/Vita3K/vita3k/lang/include -I/home/cobalt/Vita3K/vita3k/compat/include -I/home/cobalt/Vita3K/vita3k/gui/include -I/home/cobalt/Vita3K/vita3k -I/home/cobalt/Vita3K/vita3k/app/include -I/home/cobalt/Vita3K/vita3k/ime/include -I/home/cobalt/Vita3K/external/imgui -I/home/cobalt/Vita3K/external/imgui_club/imgui_memory_editor -I/home/cobalt/Vita3K/vita3k/glutil/include -I/home/cobalt/Vita3K/external/glad/include -I/home/cobalt/Vita3K/external/tracy -I/home/cobalt/Vita3K/vita3k/io/include -I/home/cobalt/Vita3K/external/better-enums -I/home/cobalt/Vita3K/vita3k/rtc/include -I/home/cobalt/Vita3K/vita3k/display/include -I/home/cobalt/Vita3K/vita3k/kernel/include -I/home/cobalt/Vita3K/vita3k/cpu/include -I/home/cobalt/Vita3K/vita3k/nids/include -I/home/cobalt/Vita3K/vita3k/gxm/include -I/home/cobalt/Vita3K/vita3k/net/include -I/home/cobalt/Vita3K/vita3k/ngs/include -I/home/cobalt/Vita3K/vita3k/packages/include -I/home/cobalt/Vita3K/vita3k/renderer/include -I/home/cobalt/Vita3K/vita3k/crypto/include -I/home/cobalt/Vita3K/external/dlmalloc -I/home/cobalt/Vita3K/external/stb -I/home/cobalt/Vita3K/vita3k/shader/include -I/home/cobalt/Vita3K/vita3k/features/include -I/home/cobalt/Vita3K/vita3k/threads/include -I/home/cobalt/Vita3K/vita3k/vkutil/include -I/home/cobalt/Vita3K/external/Vulkan-Headers/include -I/home/cobalt/Vita3K/external/VulkanMemoryAllocator-Hpp/include -I/home/cobalt/Vita3K/external/VulkanMemoryAllocator-Hpp/VulkanMemoryAllocator/include -I/home/cobalt/Vita3K/vita3k/touch/include -I/home/cobalt/Vita3K/external/xxHash/cmake_unofficial/.. -I/home/cobalt/Vita3K/vita3k/module/include -I/home/cobalt/Vita3K/external/printf -g -Wformat -Werror=format-security -std=c++20 -MD -MT vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibc/SceLibc.cpp.o -MF vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibc/SceLibc.cpp.o.d -o vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibc/SceLibc.cpp.o -c /home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.cpp
In file included from /home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.cpp:20:
In file included from /home/cobalt/Vita3K/vita3k/io/include/io/functions.h:24:
In file included from /home/cobalt/Vita3K/vita3k/io/include/io/state.h:21:
In file included from /home/cobalt/Vita3K/vita3k/io/include/io/types.h:25:
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:30:12: error: invalid operands to binary expression ('std::stringstream' (aka 'basic_stringstream<char>') and 'std::__va_list')
    datass << data;
    ~~~~~~ ^  ~~~~
/home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.cpp:1494:5: note: in instantiation of function template specialization 'to_debug_str<std::__va_list>' requested here
    TRACY_FUNC(vsnprintf, s, n, format, arg);
    ^
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:141:31: note: expanded from macro 'TRACY_FUNC'
#define TRACY_FUNC(name, ...) __TRACY_FUNC(tracy_module_name, name, ##__VA_ARGS__, , , , , , , , , )
                              ^
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:110:9: note: expanded from macro '__TRACY_FUNC'
        __TRACY_LOG_ARG_IF(arg4)                                                                                                                        \
        ^
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:99:33: note: expanded from macro '__TRACY_LOG_ARG_IF'
#define __TRACY_LOG_ARG_IF(arg) __TRACY_LOG_ARG_IF2(dummy, arg)
                                ^
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:97:52: note: expanded from macro '__TRACY_LOG_ARG_IF2'
#define __TRACY_LOG_ARG_IF2(dummy, ...) __VA_OPT__(__TRACY_LOG_ARG_IF3(__VA_ARGS__))
                                                   ^
/home/cobalt/Vita3K/vita3k/util/include/util/tracy.h:93:49: note: expanded from macro '__TRACY_LOG_ARG_IF3'
        const std::string arg_str = #arg ": " + to_debug_str(emuenv.mem, arg); \
                                                ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/system_error:279:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const std::error_code' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/cstddef:123:5: note: candidate function template not viable: no known conversion from 'std::stringstream' (aka 'basic_stringstream<char>') to 'std::byte' for 1st argument
    operator<<(byte __b, _IntegerType __shift) noexcept
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:517:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'char' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __out, char __c)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:523:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'char' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, char __c)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:534:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'signed char' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, signed char __c)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:539:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'unsigned char' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, unsigned char __c)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:548:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'wchar_t' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, wchar_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:553:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'char8_t' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, char8_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:558:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'char16_t' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, char16_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:562:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'char32_t' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, char32_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:615:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const char *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, const char* __s)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:628:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const signed char *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, const signed char* __s)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:633:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const unsigned char *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>& __out, const unsigned char* __s)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:642:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const wchar_t *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, const wchar_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:647:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const char8_t *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, const char8_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:652:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const char16_t *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, const char16_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:656:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const char32_t *' for 2nd argument
    operator<<(basic_ostream<char, _Traits>&, const char32_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/bits/ostream.tcc:302:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'const char *' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __out, const char* __s)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/thread:92:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'thread::id' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __out, thread::id __id)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:79:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'std::_Resetiosflags' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Resetiosflags __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:109:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'std::_Setiosflags' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Setiosflags __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:143:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'std::_Setbase' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Setbase __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:208:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'std::_Setprecision' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Setprecision __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:238:5: note: candidate function template not viable: no known conversion from 'std::__va_list' to 'std::_Setw' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Setw __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:507:5: note: candidate template ignored: deduced conflicting types for parameter '_CharT' ('char' vs. 'std::__va_list')
    operator<<(basic_ostream<_CharT, _Traits>& __out, _CharT __c)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/string_view:672:5: note: candidate template ignored: could not match 'basic_string_view<_CharT, _Traits>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os,
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:3883:5: note: candidate template ignored: could not match 'basic_string<_CharT, _Traits, _Alloc>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os,
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:568:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, char8_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:573:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, char16_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:577:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, char32_t) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:598:5: note: candidate template ignored: could not match 'const _CharT *' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __out, const _CharT* __s)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:662:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, const char8_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:667:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, const char16_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:671:5: note: candidate template ignored: could not match 'basic_ostream' against 'basic_stringstream'
    operator<<(basic_ostream<wchar_t, _Traits>&, const char32_t*) = delete;
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:754:5: note: candidate template ignored: substitution failure [with _Ostream = std::basic_stringstream<char> &, _Tp = std::__va_list]: constraints not satisfied for alias template '__rvalue_stream_insertion_t' [with _Os = std::basic_stringstream<char> &, _Tp = std::__va_list]
    operator<<(_Ostream&& __os, const _Tp& __x)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:1137:5: note: candidate template ignored: could not match 'unique_ptr<_Tp, _Dp>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os,
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:70:5: note: candidate template ignored: could not match '__shared_ptr<_Tp, _Lp>' against 'std::__va_list'
    operator<<(std::basic_ostream<_Ch, _Tr>& __os,
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:178:5: note: candidate template ignored: could not match '_Setfill<_CharT>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Setfill<_CharT> __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:311:5: note: candidate template ignored: could not match '_Put_money<_MoneyT>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Put_money<_MoneyT> __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/iomanip:363:5: note: candidate template ignored: could not match '_Put_time<_CharT>' against 'std::__va_list'
    operator<<(basic_ostream<_CharT, _Traits>& __os, _Put_time<_CharT> __f)
    ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:108:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'std::basic_ostream<char>::__ostream_type &(*)(std::basic_ostream<char>::__ostream_type &)' (aka 'basic_ostream<char, std::char_traits<char>> &(*)(basic_ostream<char, std::char_traits<char>> &)') for 1st argument
      operator<<(__ostream_type& (*__pf)(__ostream_type&))
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:117:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'std::basic_ostream<char>::__ios_type &(*)(std::basic_ostream<char>::__ios_type &)' (aka 'basic_ios<char, std::char_traits<char>> &(*)(basic_ios<char, std::char_traits<char>> &)') for 1st argument
      operator<<(__ios_type& (*__pf)(__ios_type&))
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:127:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'std::ios_base &(*)(std::ios_base &)' for 1st argument
      operator<<(ios_base& (*__pf) (ios_base&))
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:166:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'long' for 1st argument
      operator<<(long __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:170:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'unsigned long' for 1st argument
      operator<<(unsigned long __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:174:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'bool' for 1st argument
      operator<<(bool __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:178:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'short' for 1st argument
      operator<<(short __n);
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:181:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'unsigned short' for 1st argument
      operator<<(unsigned short __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:189:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'int' for 1st argument
      operator<<(int __n);
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:192:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'unsigned int' for 1st argument
      operator<<(unsigned int __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:201:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'long long' for 1st argument
      operator<<(long long __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:205:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'unsigned long long' for 1st argument
      operator<<(unsigned long long __n)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:220:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'double' for 1st argument
      operator<<(double __f)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:224:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'float' for 1st argument
      operator<<(float __f)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:232:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'long double' for 1st argument
      operator<<(long double __f)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:245:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'const void *' for 1st argument; take the address of the argument with &
      operator<<(const void* __p)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:250:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'std::nullptr_t' for 1st argument
      operator<<(nullptr_t)
      ^
/usr/bin/../lib/gcc/aarch64-linux-gnu/12/../../../../include/c++/12/ostream:283:7: note: candidate function not viable: no known conversion from 'std::__va_list' to 'std::basic_ostream<char>::__streambuf_type *' (aka 'basic_streambuf<char, std::char_traits<char>> *') for 1st argument
      operator<<(__streambuf_type* __sb);
      ^
In file included from /home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.cpp:18:
In file included from /home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.h:20:
In file included from /home/cobalt/Vita3K/vita3k/module/include/module/module.h:20:
In file included from /home/cobalt/Vita3K/vita3k/module/include/module/bridge.h:25:
/home/cobalt/Vita3K/vita3k/module/include/module/read_arg.h:57:16: error: no matching function for call to 'read_from_gpr'
        return read_from_gpr<T>(cpu, arg);
               ^~~~~~~~~~~~~~~~
/home/cobalt/Vita3K/vita3k/module/include/module/read_arg.h:83:33: note: in instantiation of function template specialization 'read<std::__va_list>' requested here
        const ArmType bridged = read<ArmType>(cpu, args[index], mem);
                                ^
/home/cobalt/Vita3K/vita3k/module/include/module/bridge.h:39:66: note: in instantiation of function template specialization 'read<std::__va_list, 3UL, char *, unsigned long, const char *, std::__va_list>' requested here
    const Ret ret = (*export_fn)(emuenv, thread_id, export_name, read<Args, indices, Args...>(cpu, args_layout, state, emuenv.mem)...);
                                                                 ^
/home/cobalt/Vita3K/vita3k/module/include/module/bridge.h:61:9: note: in instantiation of function template specialization 'call<int, char *, unsigned long, const char *, std::__va_list, 0UL, 1UL, 2UL, 3UL>' requested here
        call(export_fn, export_name, std::get<0>(args_layout), std::get<1>(args_layout), Indices(), thread_id, cpu, emuenv);
        ^
/home/cobalt/Vita3K/vita3k/modules/SceLibc/SceLibc.cpp:2126:1: note: in instantiation of function template specialization 'bridge<int, char *, unsigned long, const char *, std::__va_list>' requested here
BRIDGE_IMPL(vsnprintf)
^
/home/cobalt/Vita3K/vita3k/module/include/module/module.h:31:58: note: expanded from macro 'BRIDGE_IMPL'
#define BRIDGE_IMPL(name) const ImportFn import_##name = bridge(&export_##name, #name);
                                                         ^
/home/cobalt/Vita3K/vita3k/module/include/module/read_arg.h:31:37: note: candidate template ignored: requirement 'sizeof(std::__va_list) <= 4' was not satisfied [with T = std::__va_list]
std::enable_if_t<sizeof(T) <= 4, T> read_from_gpr(CPUState &cpu, const ArgLayout &arg) {
                                    ^
/home/cobalt/Vita3K/vita3k/module/include/module/read_arg.h:38:37: note: candidate template ignored: requirement 'sizeof(std::__va_list) == 8' was not satisfied [with T = std::__va_list]
std::enable_if_t<sizeof(T) == 8, T> read_from_gpr(CPUState &cpu, const ArgLayout &arg) {
                                    ^
2 errors generated.
[10/229] Building CXX object vita3k/modules/CMakeFiles/modules.dir/Debug/SceLibKernel/SceLibKernel.cpp.o
ninja: build stopped: subcommand failed.
```

I've tried searching up a couple of the errors individually, no luck yet. Unlike my previous comment (which was on 18.04 with a bunch of newer libs pulled in, including Clang/LLVM), this one is on Ubuntu 22.04 - so pretty standard.

**Comment by bookmist** [comment]
Here, I think, good enough solution is to remove `arg` from this line `TRACY_FUNC(vsnprintf, s, n, format, arg);`

**Comment by Macdu** [comment]
Ah I also had this problem while compiling the android version, I forgot to add the modifications.
The reason is that you can't use the host compiler va_list object and assume it's the same as the guest va_list. Moreover calling the host vsnprintf function is wrong as some format parameter sizes can be different, `utils::snprintf` must be called instead, I fixed it.

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
