### PR TITLE
Some improve in gui & lang.

### PR DESCRIPTION
**Pull request by Croden1999**
Some improve in gui & lang.

- gui/lang: Minor lang strings code cleanup.
- gui: Unified window interface.
- gui/user management: Fixed the Open User Folder menuitem.
- lang: Remove `initial_setup` in id/ms.xml. Because not official language on PS Vita, and also the reason is couldn't change user language in Initial Setup.
- gui/settings dialog: Add ua (Ukraine language) user language. translation by @Valeriy-Lednikov (#3220)

image
image

### CODE REVIEW

**Comment by Zangetsu38** [comment]
no understund, why adding Ukraine if no translate ? 🤔

**Comment by Zangetsu38** [comment]
> > no understund, why adding Ukraine if no translate ? 🤔
> 
> 'cause this PR, sir. #3220

I see but or is not ready, so for now no have sense adding empty file like that 🤔

**Comment by Croden1999** [comment]
> I see but or is not ready, so for now no have sense adding empty file like that 🤔

Yes, you are right, sir.

**Comment by Macdu** [comment]
@Croden1999 As PR #3220 does not seem to be getting updated, if it's fine with you, you can add the entry for the ukrainian translation along with the translation file from this PR in another commit (just add @Valerii-Lednikov as a author/co-author).

**Comment by Croden1999** [comment]
> @Croden1999 As PR #3220 does not seem to be getting updated, if it's fine with you, you can add the entry for the ukrainian translation along with the translation file from this PR in another commit (just add @Valerii-Lednikov as a author/co-author).

Okay, sir.

**Comment by Zangetsu38** [comment]
> @Croden1999 As PR #3220 does not seem to be getting updated, if it's fine with you, you can add the entry for the ukrainian translation along with the translation file from this PR in another commit (just add @Valerii-Lednikov as a author/co-author).

yes, is what i have thinks too but inside this pr directly ^^

**Comment by Croden1999** [comment]
Done

**Review by Zangetsu38 — APPROVED** [review]

**Review by Macdu — APPROVED** [review]

**Comment by Macdu** [comment]
@Croden1999 Can you rename your first commit to gui,lang: cleanup and improvements (or something similar), I can't rename your commit without squashing and I'd rather no do this in this case.

**Comment by Croden1999** [comment]
> @Croden1999 Can you rename your first commit to gui,lang: cleanup and improvements (or something similar), I can't rename your commit without squashing and I'd rather no do this in this case.

Okay, sir.

**Comment by Croden1999** [comment]
Done, Mr. @Macdu.

**Review by Macdu — APPROVED** [review]

**Pull request merged**
