### PR TITLE
Fix Linux CI build issue related to libatrac9

### PR DESCRIPTION
**Pull request by hobyst**
PR to solve issue #1532.

### CODE REVIEW

**Comment by sunho** [comment]
why is this draft?

**Comment by qurious-pixel** [comment]
```
if(WIN32)
  add_library(libatrac9 SHARED ${LIBATRAC9_SOURCES})
else()
  add_library(libatrac9 STATIC ${LIBATRAC9_SOURCES})
endif()
```
Windows complains of linkages if left static.

**Comment by hobyst** [comment]
> why is this draft?

I created the draft so that I can test changes against the CI workflows of the repository.

**Review by qurious-pixel — COMMENTED** [review]
Duplicating these lines for MSVC.

```
set_target_properties(libatrac9 PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
```

**Comment by Zangetsu38** [comment]
@hobyst oh ba :D double code set, remove one lol

**Comment by hobyst** [comment]
> Duplicating these lines for MSVC.
> 
> ```
> set_target_properties(libatrac9 PROPERTIES
> 	RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
> ```

Done. I've checked on both Windows and Linux and everything seems fine.

**Pull request merged**
