### PR TITLE
renderer: use reinterpret_cast for GLAD-related macros

### PR DESCRIPTION
**Pull request by totlmstr**
This is the first of two bugfixes while working on #660.

MSVC has been complaining about how it cannot convert the `glad.h` macros in `renderer.cpp` to their respective `Generator`/`Deleter` typedefs, and how it cannot convert `debug_output_callback` to expected `GLDEBUGPROC`. This fixes both.

### CODE REVIEW

**Comment by totlmstr** [comment]
Ran `format.bat`, but all of the changes are not in the first commit here. With that in mind, I made it a separate commit.

**Comment by VelocityRa** [comment]
Wow that's a lot of stuff...
@Zangetsu38 We should merge this right? I recall some issues with clang-format that reverted changes back and forth or it's fine?

**Comment by Zangetsu38** [comment]
i have see same recently, no idea why, maybe visual studio update for me 🤔  have get also big change on projuect after run format, but ni have cancel it in my cas,e i have thinks i have problem in local but maybe not so lol

**Comment by 1whatleytay** [comment]
LOL

This is entirely my fault. I should've figured this would happen after taking them from vitaheaders. I mean the other `Sce` structs comply with clang format, so these should too. I think this is okay to merge.

**Comment by 1whatleytay** [comment]
Ahh damn, if you can fix conflicts I will merge

**Comment by totlmstr** [comment]
Done.

Also reran `format.bat` as a sanity check. >.>

**Comment by 1whatleytay** [comment]
@VelocityRa Merging is blocked for me, mind if you approve it?

**Pull request merged**
