### PR TITLE
cpu/Kernel works

### PR DESCRIPTION
**Pull request by Zangetsu38**

### CODE REVIEW

**Review by sunho — APPROVED** [review]
Yes yes we needed this.

**Comment by sunho** [comment]
@pent0 can you remove that mem/allocator

**Comment by pent0** [comment]
Its optimised allocator i took from a kernel code of my emulator. Just a general bit allocator. In deferred branch

**Comment by sunho** [comment]
I see so we should merge deferred first

**Comment by pent0** [comment]
I told Zang to cherry pick the commit allocator first. Maybe you need time to review deferred.

**Comment by Zangetsu38** [comment]
set on other deferred pr, is no possible split both

**Pull request closed without merging**
