### PR TITLE
init support some languague in gui

### PR DESCRIPTION
**Pull request by Zangetsu38**
- Add french, italian, rusian, Spanish, korean, japanase, chinese trad and simpl language for some things in gui

# State
- [x] start screen
- [x] main menu bar (ignpore debug menu off course)
- [x] information app
- [x] settings 
 
# Result:
- french
image
image
image
image
image
image
image

- Rusian 
image
image

### CODE REVIEW

**Review by Croden1999 — COMMENTED** [review]
I want to submit zh.xml and ch.xml two translate files. 
[zh.txt](https://github.com/Vita3K/Vita3K/files/5846659/zh.txt)

**Review by Croden1999 — COMMENTED** [review]
And this. 
[ch.txt](https://github.com/Vita3K/Vita3K/files/5846581/ch.txt)

**Comment by Zangetsu38** [comment]
> And this.
> [ch.txt](https://github.com/Vita3K/Vita3K/files/5846662/ch.txt)

Thx

**Comment by Zangetsu38** [comment]
> 
> 
> I want to submit zh.xml and ch.xml two translate files.
> [zh.txt](https://github.com/Vita3K/Vita3K/files/5846659/zh.txt)

i have added both with fix some things inside

**Comment by Croden1999** [comment]
> > 我要提交zh.xml和ch.xml两个转换文件。
> > [zh.txt](https://github.com/Vita3K/Vita3K/files/5846659/zh.txt)
> 
> 我已经添加了两个修复里面的东西

Thank you very much.

**Comment by sakloui** [comment]
[nl.txt](https://github.com/Vita3K/Vita3K/files/5850843/nl.txt)
[en.txt](https://github.com/Vita3K/Vita3K/files/5850844/en.txt)

I would like to submit the Dutch translation
The English translation can be added as well but is not necessary per se, but I added it so it's easier for other languages to be translated

**Comment by Zangetsu38** [comment]
> 
> 
> [nl.txt](https://github.com/Vita3K/Vita3K/files/5850843/nl.txt)
> [en.txt](https://github.com/Vita3K/Vita3K/files/5850844/en.txt)
> 
> I would like to submit the Dutch translation
> The English translation can be added as well but is not necessary per se, but I added it so it's easier for other languages to be translated

thx, i have push after fix some things in nl

**Comment by Croden1999** [comment]
I want to resubmit these two translation files. fix text translation issues. 
Such as, 
          <wday>
		<day>星期日</day>
		<day>星期一</day>
		<day>星期二</day>
		<day>星期三</day>
		<day>星期四</day>
		<day>星期五</day>
		<day>星期六</day>
	</wday>

[zh-s.txt](https://github.com/Vita3K/Vita3K/files/5852425/zh-s.txt)
[zh-t.txt](https://github.com/Vita3K/Vita3K/files/5852426/zh-t.txt)

Please forgive me for my mistake.

**Comment by Zangetsu38** [comment]
> 
> 
> I want to resubmit these two translation files, fix text translation issues.
> Such as,
> 
> 星期日
> 星期一
> 星期二
> 星期三
> 星期四
> 星期五
> 星期六
> 
> [zh-s.txt](https://github.com/Vita3K/Vita3K/files/5852425/zh-s.txt)
> [zh-t.txt](https://github.com/Vita3K/Vita3K/files/5852426/zh-t.txt)
> 
> Please forgive me for my mistake.

is fine :)

**Comment by Croden1999** [comment]
> > 我想重新提交这两个翻译文件，解决文本翻译问题。
> > 如，
> > 星期日
> > 星期一
> > 星期二
> > 星期三
> > 星期四
> > 星期五
> > 星期六
> > [zh-s.txt ](https://github.com/Vita3K/Vita3K/files/5852425/zh-s.txt)
> > [zh-t.txt](https://github.com/Vita3K/Vita3K/files/5852426/zh-t.txt)
> > 请原谅我的错误。
> 
> 很好:)

Thank U very much.  XD

**Comment by Croden1999** [comment]
I want request to fix the translation in zh-s.xml. 
<emulation name="模拟">

To give my best respect for you.

**Comment by Zangetsu38** [comment]
> 
> 
> I want request to fix the translation in zh-s.xml.
> 
> emulation name="模拟"
> 
> To give my best respect for you.

this word not works on simplified
image

**Comment by Croden1999** [comment]
> > I want request to fix the translation in zh-s.xml.
> > emulation name="模拟"
> > To give my best respect for you.
> 
> this word not works on simplified
> image

Nevermind. I just want to fix the translation. You helped us a lot. I just want to say thank U so much.

**Comment by Zangetsu38** [comment]
> 
> 
> > > I want request to fix the translation in zh-s.xml.
> > > emulation name="模拟"
> > > To give my best respect for you.
> > 
> > 
> > this word not works on simplified
> > image
> 
> Nevermind. I just want to fix the translation. You helped us a lot. I am so excited. Thank U so much. XD

yes but probleme, this word no works on simplified :D

**Comment by Croden1999** [comment]
> > Nevermind. I just want to fix the translation. You helped us a lot. I am so excited. Thank U so much. XD
> 
> yes but probleme, this word no works on simplified :D

I want to change this word is "运行", is that OK?

**Comment by Zangetsu38** [comment]
> 
> 
> > > Nevermind. I just want to fix the translation. You helped us a lot. I am so excited. Thank U so much. XD
> > 
> > 
> > yes but probleme, this word no works on simplified :D
> 
> I want to change this word is "运行", is that OK?

i thinks yes
image

**Comment by Croden1999** [comment]
> > > > Nevermind. I just want to fix the translation. You helped us a lot. I am so excited. Thank U so much. XD
> > > 
> > > 
> > > yes but probleme, this word no works on simplified :D
> > 
> > 
> > I want to change this word is "运行", is that OK?
> 
> i thinks yes
> image
> but thuis word no have any relate emulation, it wan,t said run 🤔

it is ok. in our country, this word "模拟" and this word "运行" they have similar meanings. thank u so so much.

**Review by frangarcj — APPROVED** [review]
Lgtm

**Pull request merged**
