### PR TITLE
Update Russian (100%)

### PR DESCRIPTION
**Pull request by Danik2343**
Update Russian (100%)

### CODE REVIEW

**Comment by Danik2343** [comment]
I checked it on my own assembly, the text intersects, additional processing is needed! Russian language.

**Comment by Zangetsu38** [comment]
Revert string change, i using official psvita string

**Comment by Danik2343** [comment]
What needs to be done now? Translation updated. I only translate projects.

**Comment by Zangetsu38** [comment]
don't touch on exist strin, is already fine

**Review by Zangetsu38 — APPROVED** [review]

**Pull request merged**
